[package]
name = "goldsrc-api"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Pure Rust traits (interfaces) for GoldSrc engine interaction"

[dependencies]
goldsrc-spi = { workspace = true }
goldsrc-sys = { workspace = true, optional = true }
wit-bindgen = { workspace = true }
toml = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
log = { workspace = true }

[features]
default = ["serde", "toml", "rules", "gamedata"]
serde = ["dep:serde", "goldsrc-spi/serde"]
toml = ["dep:toml"]
rules = ["serde", "toml"]
gamedata = ["serde", "toml"]
unsafe-sys = ["dep:goldsrc-sys"]
