[package]
name = "test_i18n"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Multilingual i18n & Localization verification plugin for GoldSrc.rs"

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
goldsrc = { workspace = true }
