/* automatically generated by rust-bindgen 0.73.2 */

pub const FL_FLY: u32 = 1;
pub const FL_SWIM: u32 = 2;
pub const FL_CONVEYOR: u32 = 4;
pub const FL_CLIENT: u32 = 8;
pub const FL_INWATER: u32 = 16;
pub const FL_MONSTER: u32 = 32;
pub const FL_GODMODE: u32 = 64;
pub const FL_NOTARGET: u32 = 128;
pub const FL_SKIPLOCALHOST: u32 = 256;
pub const FL_ONGROUND: u32 = 512;
pub const FL_PARTIALGROUND: u32 = 1024;
pub const FL_WATERJUMP: u32 = 2048;
pub const FL_FROZEN: u32 = 4096;
pub const FL_FAKECLIENT: u32 = 8192;
pub const FL_DUCKING: u32 = 16384;
pub const FL_FLOAT: u32 = 32768;
pub const FL_GRAPHED: u32 = 65536;
pub const FL_IMMUNE_WATER: u32 = 131072;
pub const FL_IMMUNE_SLIME: u32 = 262144;
pub const FL_IMMUNE_LAVA: u32 = 524288;
pub const FL_PROXY: u32 = 1048576;
pub const FL_ALWAYSTHINK: u32 = 2097152;
pub const FL_BASEVELOCITY: u32 = 4194304;
pub const FL_MONSTERCLIP: u32 = 8388608;
pub const FL_ONTRAIN: u32 = 16777216;
pub const FL_WORLDBRUSH: u32 = 33554432;
pub const FL_SPECTATOR: u32 = 67108864;
pub const FL_CUSTOMENTITY: u32 = 536870912;
pub const FL_KILLME: u32 = 1073741824;
pub const FL_DORMANT: u32 = 2147483648;
pub const FTRACE_SIMPLEBOX: u32 = 1;
pub const WALKMOVE_NORMAL: u32 = 0;
pub const WALKMOVE_WORLDONLY: u32 = 1;
pub const WALKMOVE_CHECKONLY: u32 = 2;
pub const MOVETYPE_NONE: u32 = 0;
pub const MOVETYPE_WALK: u32 = 3;
pub const MOVETYPE_STEP: u32 = 4;
pub const MOVETYPE_FLY: u32 = 5;
pub const MOVETYPE_TOSS: u32 = 6;
pub const MOVETYPE_PUSH: u32 = 7;
pub const MOVETYPE_NOCLIP: u32 = 8;
pub const MOVETYPE_FLYMISSILE: u32 = 9;
pub const MOVETYPE_BOUNCE: u32 = 10;
pub const MOVETYPE_BOUNCEMISSILE: u32 = 11;
pub const MOVETYPE_FOLLOW: u32 = 12;
pub const MOVETYPE_PUSHSTEP: u32 = 13;
pub const SOLID_NOT: u32 = 0;
pub const SOLID_TRIGGER: u32 = 1;
pub const SOLID_BBOX: u32 = 2;
pub const SOLID_SLIDEBOX: u32 = 3;
pub const SOLID_BSP: u32 = 4;
pub const DEAD_NO: u32 = 0;
pub const DEAD_DYING: u32 = 1;
pub const DEAD_DEAD: u32 = 2;
pub const DEAD_RESPAWNABLE: u32 = 3;
pub const DEAD_DISCARDBODY: u32 = 4;
pub const DAMAGE_NO: u32 = 0;
pub const DAMAGE_YES: u32 = 1;
pub const DAMAGE_AIM: u32 = 2;
pub const EF_BRIGHTFIELD: u32 = 1;
pub const EF_MUZZLEFLASH: u32 = 2;
pub const EF_BRIGHTLIGHT: u32 = 4;
pub const EF_DIMLIGHT: u32 = 8;
pub const EF_INVLIGHT: u32 = 16;
pub const EF_NOINTERP: u32 = 32;
pub const EF_LIGHT: u32 = 64;
pub const EF_NODRAW: u32 = 128;
pub const EF_NIGHTVISION: u32 = 256;
pub const EF_SNIPERLASER: u32 = 512;
pub const EF_FIBERCAMERA: u32 = 1024;
pub const EFLAG_SLERP: u32 = 1;
pub const TE_BEAMPOINTS: u32 = 0;
pub const TE_BEAMENTPOINT: u32 = 1;
pub const TE_GUNSHOT: u32 = 2;
pub const TE_EXPLOSION: u32 = 3;
pub const TE_EXPLFLAG_NONE: u32 = 0;
pub const TE_EXPLFLAG_NOADDITIVE: u32 = 1;
pub const TE_EXPLFLAG_NODLIGHTS: u32 = 2;
pub const TE_EXPLFLAG_NOSOUND: u32 = 4;
pub const TE_EXPLFLAG_NOPARTICLES: u32 = 8;
pub const TE_TAREXPLOSION: u32 = 4;
pub const TE_SMOKE: u32 = 5;
pub const TE_TRACER: u32 = 6;
pub const TE_LIGHTNING: u32 = 7;
pub const TE_BEAMENTS: u32 = 8;
pub const TE_SPARKS: u32 = 9;
pub const TE_LAVASPLASH: u32 = 10;
pub const TE_TELEPORT: u32 = 11;
pub const TE_EXPLOSION2: u32 = 12;
pub const TE_BSPDECAL: u32 = 13;
pub const TE_IMPLOSION: u32 = 14;
pub const TE_SPRITETRAIL: u32 = 15;
pub const TE_BEAM: u32 = 16;
pub const TE_SPRITE: u32 = 17;
pub const TE_BEAMSPRITE: u32 = 18;
pub const TE_BEAMTORUS: u32 = 19;
pub const TE_BEAMDISK: u32 = 20;
pub const TE_BEAMCYLINDER: u32 = 21;
pub const TE_BEAMFOLLOW: u32 = 22;
pub const TE_GLOWSPRITE: u32 = 23;
pub const TE_BEAMRING: u32 = 24;
pub const TE_STREAK_SPLASH: u32 = 25;
pub const TE_BEAMHOSE: u32 = 26;
pub const TE_DLIGHT: u32 = 27;
pub const TE_ELIGHT: u32 = 28;
pub const TE_TEXTMESSAGE: u32 = 29;
pub const TE_LINE: u32 = 30;
pub const TE_BOX: u32 = 31;
pub const TE_KILLBEAM: u32 = 99;
pub const TE_LARGEFUNNEL: u32 = 100;
pub const TE_BLOODSTREAM: u32 = 101;
pub const TE_SHOWLINE: u32 = 102;
pub const TE_BLOOD: u32 = 103;
pub const TE_DECAL: u32 = 104;
pub const TE_FIZZ: u32 = 105;
pub const TE_MODEL: u32 = 106;
pub const TE_EXPLODEMODEL: u32 = 107;
pub const TE_BREAKMODEL: u32 = 108;
pub const TE_GUNSHOTDECAL: u32 = 109;
pub const TE_SPRITE_SPRAY: u32 = 110;
pub const TE_ARMOR_RICOCHET: u32 = 111;
pub const TE_PLAYERDECAL: u32 = 112;
pub const TE_BUBBLES: u32 = 113;
pub const TE_BUBBLETRAIL: u32 = 114;
pub const TE_BLOODSPRITE: u32 = 115;
pub const TE_WORLDDECAL: u32 = 116;
pub const TE_WORLDDECALHIGH: u32 = 117;
pub const TE_DECALHIGH: u32 = 118;
pub const TE_PROJECTILE: u32 = 119;
pub const TE_SPRAY: u32 = 120;
pub const TE_PLAYERSPRITES: u32 = 121;
pub const TE_PARTICLEBURST: u32 = 122;
pub const TE_FIREFIELD: u32 = 123;
pub const TEFIRE_FLAG_ALLFLOAT: u32 = 1;
pub const TEFIRE_FLAG_SOMEFLOAT: u32 = 2;
pub const TEFIRE_FLAG_LOOP: u32 = 4;
pub const TEFIRE_FLAG_ALPHA: u32 = 8;
pub const TEFIRE_FLAG_PLANAR: u32 = 16;
pub const TEFIRE_FLAG_ADDITIVE: u32 = 32;
pub const TE_PLAYERATTACHMENT: u32 = 124;
pub const TE_KILLPLAYERATTACHMENTS: u32 = 125;
pub const TE_MULTIGUNSHOT: u32 = 126;
pub const TE_USERTRACER: u32 = 127;
pub const MSG_BROADCAST: u32 = 0;
pub const MSG_ONE: u32 = 1;
pub const MSG_ALL: u32 = 2;
pub const MSG_INIT: u32 = 3;
pub const MSG_PVS: u32 = 4;
pub const MSG_PAS: u32 = 5;
pub const MSG_PVS_R: u32 = 6;
pub const MSG_PAS_R: u32 = 7;
pub const MSG_ONE_UNRELIABLE: u32 = 8;
pub const MSG_SPEC: u32 = 9;
pub const CONTENTS_EMPTY: i32 = -1;
pub const CONTENTS_SOLID: i32 = -2;
pub const CONTENTS_WATER: i32 = -3;
pub const CONTENTS_SLIME: i32 = -4;
pub const CONTENTS_LAVA: i32 = -5;
pub const CONTENTS_SKY: i32 = -6;
pub const CONTENTS_LADDER: i32 = -16;
pub const CONTENT_FLYFIELD: i32 = -17;
pub const CONTENT_GRAVITY_FLYFIELD: i32 = -18;
pub const CONTENT_FOG: i32 = -19;
pub const CONTENT_EMPTY: i32 = -1;
pub const CONTENT_SOLID: i32 = -2;
pub const CONTENT_WATER: i32 = -3;
pub const CONTENT_SLIME: i32 = -4;
pub const CONTENT_LAVA: i32 = -5;
pub const CONTENT_SKY: i32 = -6;
pub const CHAN_AUTO: u32 = 0;
pub const CHAN_WEAPON: u32 = 1;
pub const CHAN_VOICE: u32 = 2;
pub const CHAN_ITEM: u32 = 3;
pub const CHAN_BODY: u32 = 4;
pub const CHAN_STREAM: u32 = 5;
pub const CHAN_STATIC: u32 = 6;
pub const CHAN_NETWORKVOICE_BASE: u32 = 7;
pub const CHAN_NETWORKVOICE_END: u32 = 500;
pub const CHAN_BOT: u32 = 501;
pub const ATTN_NONE: u32 = 0;
pub const PITCH_NORM: u32 = 100;
pub const PITCH_LOW: u32 = 95;
pub const PITCH_HIGH: u32 = 120;
pub const VOL_NORM: f64 = 1.0;
pub const PLAT_LOW_TRIGGER: u32 = 1;
pub const SF_TRAIN_WAIT_RETRIGGER: u32 = 1;
pub const SF_TRAIN_START_ON: u32 = 4;
pub const SF_TRAIN_PASSABLE: u32 = 8;
pub const IN_ATTACK: u32 = 1;
pub const IN_JUMP: u32 = 2;
pub const IN_DUCK: u32 = 4;
pub const IN_FORWARD: u32 = 8;
pub const IN_BACK: u32 = 16;
pub const IN_USE: u32 = 32;
pub const IN_CANCEL: u32 = 64;
pub const IN_LEFT: u32 = 128;
pub const IN_RIGHT: u32 = 256;
pub const IN_MOVELEFT: u32 = 512;
pub const IN_MOVERIGHT: u32 = 1024;
pub const IN_ATTACK2: u32 = 2048;
pub const IN_RUN: u32 = 4096;
pub const IN_RELOAD: u32 = 8192;
pub const IN_ALT1: u32 = 16384;
pub const IN_SCORE: u32 = 32768;
pub const BREAK_TYPEMASK: u32 = 79;
pub const BREAK_GLASS: u32 = 1;
pub const BREAK_METAL: u32 = 2;
pub const BREAK_FLESH: u32 = 4;
pub const BREAK_WOOD: u32 = 8;
pub const BREAK_SMOKE: u32 = 16;
pub const BREAK_TRANS: u32 = 32;
pub const BREAK_CONCRETE: u32 = 64;
pub const BREAK_2: u32 = 128;
pub const BOUNCE_GLASS: u32 = 1;
pub const BOUNCE_METAL: u32 = 2;
pub const BOUNCE_FLESH: u32 = 4;
pub const BOUNCE_WOOD: u32 = 8;
pub const BOUNCE_SHRAP: u32 = 16;
pub const BOUNCE_SHELL: u32 = 32;
pub const BOUNCE_CONCRETE: u32 = 64;
pub const BOUNCE_SHOTSHELL: u32 = 128;
pub const TE_BOUNCE_NULL: u32 = 0;
pub const TE_BOUNCE_SHELL: u32 = 1;
pub const TE_BOUNCE_SHOTSHELL: u32 = 2;
pub const MAX_ENT_LEAFS: u32 = 48;
pub const k_cubSaltSize: u32 = 8;
pub const INTERFACE_VERSION: u32 = 140;
pub const _VCRT_COMPILER_PREPROCESSOR: u32 = 1;
pub const _SAL_VERSION: u32 = 20;
pub const __SAL_H_VERSION: u32 = 180000000;
pub const _USE_DECLSPECS_FOR_SAL: u32 = 0;
pub const _USE_ATTRIBUTES_FOR_SAL: u32 = 0;
pub const _CRT_PACKING: u32 = 8;
pub const _HAS_EXCEPTIONS: u32 = 1;
pub const _STL_LANG: u32 = 0;
pub const _HAS_CXX17: u32 = 0;
pub const _HAS_CXX20: u32 = 0;
pub const _HAS_CXX23: u32 = 0;
pub const _HAS_CXX26: u32 = 0;
pub const _HAS_NODISCARD: u32 = 0;
pub const _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE: u32 = 1;
pub const _CRT_BUILD_DESKTOP_APP: u32 = 1;
pub const _ARGMAX: u32 = 100;
pub const _CRT_INT_MAX: u32 = 2147483647;
pub const _CRT_FUNCTIONS_REQUIRED: u32 = 1;
pub const _CRT_HAS_CXX17: u32 = 0;
pub const _CRT_HAS_C11: u32 = 1;
pub const _CRT_INTERNAL_NONSTDC_NAMES: u32 = 1;
pub const __STDC_SECURE_LIB__: u32 = 200411;
pub const __GOT_SECURE_LIB__: u32 = 200411;
pub const __STDC_WANT_SECURE_LIB__: u32 = 1;
pub const _SECURECRT_FILL_BUFFER_PATTERN: u32 = 254;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES: u32 = 1;
pub const _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY: u32 = 0;
pub const _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY: u32 = 0;
pub const _STATIC_INLINE_UCRT_FUNCTIONS: u32 = 0;
pub const _CRT_INTERNAL_STDIO_SYMBOL_PREFIX: &[u8; 1] = b"\0";
pub const _CRT_INTERNAL_PRINTF_LEGACY_VSPRINTF_NULL_TERMINATION: u32 = 1;
pub const _CRT_INTERNAL_PRINTF_STANDARD_SNPRINTF_BEHAVIOR: u32 = 2;
pub const _CRT_INTERNAL_PRINTF_LEGACY_WIDE_SPECIFIERS: u32 = 4;
pub const _CRT_INTERNAL_PRINTF_LEGACY_MSVCRT_COMPATIBILITY: u32 = 8;
pub const _CRT_INTERNAL_PRINTF_LEGACY_THREE_DIGIT_EXPONENTS: u32 = 16;
pub const _CRT_INTERNAL_PRINTF_STANDARD_ROUNDING: u32 = 32;
pub const _CRT_INTERNAL_SCANF_SECURECRT: u32 = 1;
pub const _CRT_INTERNAL_SCANF_LEGACY_WIDE_SPECIFIERS: u32 = 2;
pub const _CRT_INTERNAL_SCANF_LEGACY_MSVCRT_COMPATIBILITY: u32 = 4;
pub const BUFSIZ: u32 = 512;
pub const _NSTREAM_: u32 = 512;
pub const _IOB_ENTRIES: u32 = 3;
pub const EOF: i32 = -1;
pub const _IOFBF: u32 = 0;
pub const _IOLBF: u32 = 64;
pub const _IONBF: u32 = 4;
pub const L_tmpnam: u32 = 260;
pub const L_tmpnam_s: u32 = 260;
pub const SEEK_CUR: u32 = 1;
pub const SEEK_END: u32 = 2;
pub const SEEK_SET: u32 = 0;
pub const FILENAME_MAX: u32 = 260;
pub const FOPEN_MAX: u32 = 20;
pub const _SYS_OPEN: u32 = 20;
pub const TMP_MAX: u32 = 2147483647;
pub const TMP_MAX_S: u32 = 2147483647;
pub const _TMP_MAX_S: u32 = 2147483647;
pub const SYS_OPEN: u32 = 20;
pub const MAX_QPATH: u32 = 64;
pub const RES_FATALIFMISSING: u32 = 1;
pub const RES_WASMISSING: u32 = 2;
pub const RES_CUSTOM: u32 = 4;
pub const RES_REQUESTED: u32 = 8;
pub const RES_PRECACHED: u32 = 16;
pub const RES_ALWAYS: u32 = 32;
pub const RES_CHECKFILE: u32 = 128;
pub const FCUST_FROMHPAK: u32 = 1;
pub const FCUST_WIPEDATA: u32 = 2;
pub const FCUST_IGNOREINIT: u32 = 4;
pub const FCVAR_ARCHIVE: u32 = 1;
pub const FCVAR_USERINFO: u32 = 2;
pub const FCVAR_SERVER: u32 = 4;
pub const FCVAR_EXTDLL: u32 = 8;
pub const FCVAR_CLIENTDLL: u32 = 16;
pub const FCVAR_PROTECTED: u32 = 32;
pub const FCVAR_SPONLY: u32 = 64;
pub const FCVAR_PRINTABLEONLY: u32 = 128;
pub const FCVAR_UNLOGGED: u32 = 256;
pub const FCVAR_NOEXTRAWHITEPACE: u32 = 512;
pub const MAX_LEVEL_CONNECTIONS: u32 = 16;
pub const FENTTABLE_PLAYER: u32 = 2147483648;
pub const FENTTABLE_REMOVED: u32 = 1073741824;
pub const FENTTABLE_MOVEABLE: u32 = 536870912;
pub const FENTTABLE_GLOBAL: u32 = 268435456;
pub const FTYPEDESC_GLOBAL: u32 = 1;
pub const NEW_DLL_FUNCTIONS_VERSION: u32 = 1;
pub type string_t = ::std::os::raw::c_uint;
pub type vec_t = f32;
pub type vec3_t = [vec_t; 3usize];
pub const kRenderNormal: _bindgen_ty_1 = 0;
pub const kRenderTransColor: _bindgen_ty_1 = 1;
pub const kRenderTransTexture: _bindgen_ty_1 = 2;
pub const kRenderGlow: _bindgen_ty_1 = 3;
pub const kRenderTransAlpha: _bindgen_ty_1 = 4;
pub const kRenderTransAdd: _bindgen_ty_1 = 5;
pub type _bindgen_ty_1 = ::std::os::raw::c_int;
pub const kRenderFxNone: _bindgen_ty_2 = 0;
pub const kRenderFxPulseSlow: _bindgen_ty_2 = 1;
pub const kRenderFxPulseFast: _bindgen_ty_2 = 2;
pub const kRenderFxPulseSlowWide: _bindgen_ty_2 = 3;
pub const kRenderFxPulseFastWide: _bindgen_ty_2 = 4;
pub const kRenderFxFadeSlow: _bindgen_ty_2 = 5;
pub const kRenderFxFadeFast: _bindgen_ty_2 = 6;
pub const kRenderFxSolidSlow: _bindgen_ty_2 = 7;
pub const kRenderFxSolidFast: _bindgen_ty_2 = 8;
pub const kRenderFxStrobeSlow: _bindgen_ty_2 = 9;
pub const kRenderFxStrobeFast: _bindgen_ty_2 = 10;
pub const kRenderFxStrobeFaster: _bindgen_ty_2 = 11;
pub const kRenderFxFlickerSlow: _bindgen_ty_2 = 12;
pub const kRenderFxFlickerFast: _bindgen_ty_2 = 13;
pub const kRenderFxNoDissipation: _bindgen_ty_2 = 14;
pub const kRenderFxDistort: _bindgen_ty_2 = 15;
pub const kRenderFxHologram: _bindgen_ty_2 = 16;
pub const kRenderFxDeadPlayer: _bindgen_ty_2 = 17;
pub const kRenderFxExplode: _bindgen_ty_2 = 18;
pub const kRenderFxGlowShell: _bindgen_ty_2 = 19;
pub const kRenderFxClampMinScale: _bindgen_ty_2 = 20;
pub const kRenderFxLightMultiplier: _bindgen_ty_2 = 21;
pub type _bindgen_ty_2 = ::std::os::raw::c_int;
pub type func_t = ::std::os::raw::c_uint;
pub type byte = ::std::os::raw::c_uchar;
pub type word = ::std::os::raw::c_ushort;
pub const qboolean_false_: qboolean = 0;
pub const qboolean_true_: qboolean = 1;
pub type qboolean = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct color24 {
    pub r: byte,
    pub g: byte,
    pub b: byte,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct colorVec {
    pub r: ::std::os::raw::c_uint,
    pub g: ::std::os::raw::c_uint,
    pub b: ::std::os::raw::c_uint,
    pub a: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct PackedColorVec {
    pub r: ::std::os::raw::c_ushort,
    pub g: ::std::os::raw::c_ushort,
    pub b: ::std::os::raw::c_ushort,
    pub a: ::std::os::raw::c_ushort,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct link_s {
    pub prev: *mut link_s,
    pub next: *mut link_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type link_t = link_s;
pub type edict_t = edict_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct plane_t {
    pub normal: vec3_t,
    pub dist: f32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct trace_t {
    pub allsolid: qboolean,
    pub startsolid: qboolean,
    pub inopen: qboolean,
    pub inwater: qboolean,
    pub fraction: f32,
    pub endpos: vec3_t,
    pub plane: plane_t,
    pub ent: *mut edict_t,
    pub hitgroup: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct globalvars_t {
    pub time: f32,
    pub frametime: f32,
    pub force_retouch: f32,
    pub mapname: string_t,
    pub startspot: string_t,
    pub deathmatch: f32,
    pub coop: f32,
    pub teamplay: f32,
    pub serverflags: f32,
    pub found_secrets: f32,
    pub v_forward: vec3_t,
    pub v_up: vec3_t,
    pub v_right: vec3_t,
    pub trace_allsolid: f32,
    pub trace_startsolid: f32,
    pub trace_fraction: f32,
    pub trace_endpos: vec3_t,
    pub trace_plane_normal: vec3_t,
    pub trace_plane_dist: f32,
    pub trace_ent: *mut edict_t,
    pub trace_inopen: f32,
    pub trace_inwater: f32,
    pub trace_hitgroup: ::std::os::raw::c_int,
    pub trace_flags: ::std::os::raw::c_int,
    pub msg_entity: ::std::os::raw::c_int,
    pub cdAudioTrack: ::std::os::raw::c_int,
    pub maxClients: ::std::os::raw::c_int,
    pub maxEntities: ::std::os::raw::c_int,
    pub pStringBase: *const ::std::os::raw::c_char,
    pub pSaveData: *mut ::std::os::raw::c_void,
    pub vecLandmarkOffset: vec3_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct entvars_s {
    pub classname: string_t,
    pub globalname: string_t,
    pub origin: vec3_t,
    pub oldorigin: vec3_t,
    pub velocity: vec3_t,
    pub basevelocity: vec3_t,
    pub clbasevelocity: vec3_t,
    pub movedir: vec3_t,
    pub angles: vec3_t,
    pub avelocity: vec3_t,
    pub punchangle: vec3_t,
    pub v_angle: vec3_t,
    pub endpos: vec3_t,
    pub startpos: vec3_t,
    pub impacttime: f32,
    pub starttime: f32,
    pub fixangle: ::std::os::raw::c_int,
    pub idealpitch: f32,
    pub pitch_speed: f32,
    pub ideal_yaw: f32,
    pub yaw_speed: f32,
    pub modelindex: ::std::os::raw::c_int,
    pub model: string_t,
    pub viewmodel: ::std::os::raw::c_int,
    pub weaponmodel: ::std::os::raw::c_int,
    pub absmin: vec3_t,
    pub absmax: vec3_t,
    pub mins: vec3_t,
    pub maxs: vec3_t,
    pub size: vec3_t,
    pub ltime: f32,
    pub nextthink: f32,
    pub movetype: ::std::os::raw::c_int,
    pub solid: ::std::os::raw::c_int,
    pub skin: ::std::os::raw::c_int,
    pub body: ::std::os::raw::c_int,
    pub effects: ::std::os::raw::c_int,
    pub gravity: f32,
    pub friction: f32,
    pub light_level: ::std::os::raw::c_int,
    pub sequence: ::std::os::raw::c_int,
    pub gaitsequence: ::std::os::raw::c_int,
    pub frame: f32,
    pub animtime: f32,
    pub framerate: f32,
    pub controller: [byte; 4usize],
    pub blending: [byte; 2usize],
    pub scale: f32,
    pub rendermode: ::std::os::raw::c_int,
    pub renderamt: f32,
    pub rendercolor: vec3_t,
    pub renderfx: ::std::os::raw::c_int,
    pub health: f32,
    pub frags: f32,
    pub weapons: ::std::os::raw::c_int,
    pub takedamage: f32,
    pub deadflag: ::std::os::raw::c_int,
    pub view_ofs: vec3_t,
    pub button: ::std::os::raw::c_int,
    pub impulse: ::std::os::raw::c_int,
    pub chain: *mut edict_t,
    pub dmg_inflictor: *mut edict_t,
    pub enemy: *mut edict_t,
    pub aiment: *mut edict_t,
    pub owner: *mut edict_t,
    pub groundentity: *mut edict_t,
    pub spawnflags: ::std::os::raw::c_int,
    pub flags: ::std::os::raw::c_int,
    pub colormap: ::std::os::raw::c_int,
    pub team: ::std::os::raw::c_int,
    pub max_health: f32,
    pub teleport_time: f32,
    pub armortype: f32,
    pub armorvalue: f32,
    pub waterlevel: ::std::os::raw::c_int,
    pub watertype: ::std::os::raw::c_int,
    pub target: string_t,
    pub targetname: string_t,
    pub netname: string_t,
    pub message: string_t,
    pub dmg_take: f32,
    pub dmg_save: f32,
    pub dmg: f32,
    pub dmgtime: f32,
    pub noise: string_t,
    pub noise1: string_t,
    pub noise2: string_t,
    pub noise3: string_t,
    pub speed: f32,
    pub air_finished: f32,
    pub pain_finished: f32,
    pub radsuit_finished: f32,
    pub pContainingEntity: *mut edict_t,
    pub playerclass: ::std::os::raw::c_int,
    pub maxspeed: f32,
    pub fov: f32,
    pub weaponanim: ::std::os::raw::c_int,
    pub pushmsec: ::std::os::raw::c_int,
    pub bInDuck: ::std::os::raw::c_int,
    pub flTimeStepSound: ::std::os::raw::c_int,
    pub flSwimTime: ::std::os::raw::c_int,
    pub flDuckTime: ::std::os::raw::c_int,
    pub iStepLeft: ::std::os::raw::c_int,
    pub flFallVelocity: f32,
    pub gamestate: ::std::os::raw::c_int,
    pub oldbuttons: ::std::os::raw::c_int,
    pub groupinfo: ::std::os::raw::c_int,
    pub iuser1: ::std::os::raw::c_int,
    pub iuser2: ::std::os::raw::c_int,
    pub iuser3: ::std::os::raw::c_int,
    pub iuser4: ::std::os::raw::c_int,
    pub fuser1: f32,
    pub fuser2: f32,
    pub fuser3: f32,
    pub fuser4: f32,
    pub vuser1: vec3_t,
    pub vuser2: vec3_t,
    pub vuser3: vec3_t,
    pub vuser4: vec3_t,
    pub euser1: *mut edict_t,
    pub euser2: *mut edict_t,
    pub euser3: *mut edict_t,
    pub euser4: *mut edict_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type entvars_t = entvars_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct edict_s {
    pub free: qboolean,
    pub serialnumber: ::std::os::raw::c_int,
    pub area: link_t,
    pub headnode: ::std::os::raw::c_int,
    pub num_leafs: ::std::os::raw::c_int,
    pub leafnums: [::std::os::raw::c_short; 48usize],
    pub freetime: f32,
    pub pvPrivateData: *mut ::std::os::raw::c_void,
    pub v: entvars_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct usercmd_s {
    pub lerp_msec: ::std::os::raw::c_short,
    pub msec: byte,
    pub viewangles: vec3_t,
    pub forwardmove: f32,
    pub sidemove: f32,
    pub upmove: f32,
    pub lightlevel: byte,
    pub buttons: ::std::os::raw::c_ushort,
    pub impulse: byte,
    pub weaponselect: byte,
    pub impact_index: ::std::os::raw::c_int,
    pub impact_position: vec3_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type usercmd_t = usercmd_s;
pub type uint8 = ::std::os::raw::c_uchar;
pub type int8 = ::std::os::raw::c_schar;
pub type int16 = ::std::os::raw::c_short;
pub type uint16 = ::std::os::raw::c_ushort;
pub type int32 = ::std::os::raw::c_int;
pub type uint32 = ::std::os::raw::c_uint;
pub type int64 = ::std::os::raw::c_longlong;
pub type uint64 = ::std::os::raw::c_ulonglong;
pub type intp = ::std::os::raw::c_longlong;
pub type uintp = ::std::os::raw::c_ulonglong;
pub type Salt_t = [uint8; 8usize];
pub type GID_t = uint64;
pub type JobID_t = GID_t;
pub type TxnID_t = GID_t;
pub type PackageId_t = uint32;
pub type AppId_t = uint32;
pub type AssetClassId_t = uint64;
pub type PhysicalItemId_t = uint32;
pub type DepotId_t = uint32;
pub type RTime32 = uint32;
pub type CellID_t = uint32;
pub type SteamAPICall_t = uint64;
pub type AccountID_t = uint32;
pub type PartnerId_t = uint32;
pub type va_list = *mut ::std::os::raw::c_char;
unsafe extern "C" {
    pub fn __va_start(arg1: *mut *mut ::std::os::raw::c_char, ...);
}
pub type __vcrt_bool = bool;
pub type wchar_t = ::std::os::raw::c_ushort;
unsafe extern "C" {
    pub fn __security_init_cookie();
}
unsafe extern "C" {
    pub fn __security_check_cookie(_StackCookie: usize);
}
unsafe extern "C" {
    pub fn __report_gsfailure(_StackCookie: usize) -> !;
}
unsafe extern "C" {
    pub static mut __security_cookie: usize;
}
pub type __crt_bool = bool;
unsafe extern "C" {
    pub fn _invalid_parameter_noinfo();
}
unsafe extern "C" {
    pub fn _invalid_parameter_noinfo_noreturn() -> !;
}
unsafe extern "C" {
    pub fn _invoke_watson(
        _Expression: *const wchar_t,
        _FunctionName: *const wchar_t,
        _FileName: *const wchar_t,
        _LineNo: ::std::os::raw::c_uint,
        _Reserved: usize,
    ) -> !;
}
pub type errno_t = ::std::os::raw::c_int;
pub type wint_t = ::std::os::raw::c_ushort;
pub type wctype_t = ::std::os::raw::c_ushort;
pub type __time32_t = ::std::os::raw::c_long;
pub type __time64_t = ::std::os::raw::c_longlong;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data_public {
    pub _locale_pctype: *const ::std::os::raw::c_ushort,
    pub _locale_mb_cur_max: ::std::os::raw::c_int,
    pub _locale_lc_codepage: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_pointers {
    pub locinfo: *mut __crt_locale_data,
    pub mbcinfo: *mut __crt_multibyte_data,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type _locale_t = *mut __crt_locale_pointers;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _Mbstatet {
    pub _Wchar: ::std::os::raw::c_ulong,
    pub _Byte: ::std::os::raw::c_ushort,
    pub _State: ::std::os::raw::c_ushort,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {};
pub type mbstate_t = _Mbstatet;
pub type time_t = __time64_t;
pub type rsize_t = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _iobuf {
    pub _Placeholder: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type FILE = _iobuf;
unsafe extern "C" {
    pub fn __acrt_iob_func(_Ix: ::std::os::raw::c_uint) -> *mut FILE;
}
unsafe extern "C" {
    pub fn fgetwc(_Stream: *mut FILE) -> wint_t;
}
unsafe extern "C" {
    pub fn _fgetwchar() -> wint_t;
}
unsafe extern "C" {
    pub fn fputwc(_Character: wchar_t, _Stream: *mut FILE) -> wint_t;
}
unsafe extern "C" {
    pub fn _fputwchar(_Character: wchar_t) -> wint_t;
}
unsafe extern "C" {
    pub fn getwc(_Stream: *mut FILE) -> wint_t;
}
unsafe extern "C" {
    pub fn getwchar() -> wint_t;
}
unsafe extern "C" {
    pub fn fgetws(
        _Buffer: *mut wchar_t,
        _BufferCount: ::std::os::raw::c_int,
        _Stream: *mut FILE,
    ) -> *mut wchar_t;
}
unsafe extern "C" {
    pub fn fputws(_Buffer: *const wchar_t, _Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _getws_s(_Buffer: *mut wchar_t, _BufferCount: usize) -> *mut wchar_t;
}
unsafe extern "C" {
    pub fn putwc(_Character: wchar_t, _Stream: *mut FILE) -> wint_t;
}
unsafe extern "C" {
    pub fn putwchar(_Character: wchar_t) -> wint_t;
}
unsafe extern "C" {
    pub fn _putws(_Buffer: *const wchar_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn ungetwc(_Character: wint_t, _Stream: *mut FILE) -> wint_t;
}
unsafe extern "C" {
    pub fn _wfdopen(_FileHandle: ::std::os::raw::c_int, _Mode: *const wchar_t) -> *mut FILE;
}
unsafe extern "C" {
    pub fn _wfopen(_FileName: *const wchar_t, _Mode: *const wchar_t) -> *mut FILE;
}
unsafe extern "C" {
    pub fn _wfopen_s(
        _Stream: *mut *mut FILE,
        _FileName: *const wchar_t,
        _Mode: *const wchar_t,
    ) -> errno_t;
}
unsafe extern "C" {
    pub fn _wfreopen(
        _FileName: *const wchar_t,
        _Mode: *const wchar_t,
        _OldStream: *mut FILE,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn _wfreopen_s(
        _Stream: *mut *mut FILE,
        _FileName: *const wchar_t,
        _Mode: *const wchar_t,
        _OldStream: *mut FILE,
    ) -> errno_t;
}
unsafe extern "C" {
    pub fn _wfsopen(
        _FileName: *const wchar_t,
        _Mode: *const wchar_t,
        _ShFlag: ::std::os::raw::c_int,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn _wperror(_ErrorMessage: *const wchar_t);
}
unsafe extern "C" {
    pub fn _wpopen(_Command: *const wchar_t, _Mode: *const wchar_t) -> *mut FILE;
}
unsafe extern "C" {
    pub fn _wremove(_FileName: *const wchar_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _wtempnam(_Directory: *const wchar_t, _FilePrefix: *const wchar_t) -> *mut wchar_t;
}
unsafe extern "C" {
    pub fn _wtmpnam_s(_Buffer: *mut wchar_t, _BufferCount: usize) -> errno_t;
}
unsafe extern "C" {
    pub fn _wtmpnam(_Buffer: *mut wchar_t) -> *mut wchar_t;
}
unsafe extern "C" {
    pub fn _fgetwc_nolock(_Stream: *mut FILE) -> wint_t;
}
unsafe extern "C" {
    pub fn _fputwc_nolock(_Character: wchar_t, _Stream: *mut FILE) -> wint_t;
}
unsafe extern "C" {
    pub fn _getwc_nolock(_Stream: *mut FILE) -> wint_t;
}
unsafe extern "C" {
    pub fn _putwc_nolock(_Character: wchar_t, _Stream: *mut FILE) -> wint_t;
}
unsafe extern "C" {
    pub fn _ungetwc_nolock(_Character: wint_t, _Stream: *mut FILE) -> wint_t;
}
unsafe extern "C" {
    pub fn __stdio_common_vfwprintf(
        _Options: ::std::os::raw::c_ulonglong,
        _Stream: *mut FILE,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vfwprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _Stream: *mut FILE,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vfwprintf_p(
        _Options: ::std::os::raw::c_ulonglong,
        _Stream: *mut FILE,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vfwscanf(
        _Options: ::std::os::raw::c_ulonglong,
        _Stream: *mut FILE,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vswprintf(
        _Options: ::std::os::raw::c_ulonglong,
        _Buffer: *mut wchar_t,
        _BufferCount: usize,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vswprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _Buffer: *mut wchar_t,
        _BufferCount: usize,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vsnwprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _Buffer: *mut wchar_t,
        _BufferCount: usize,
        _MaxCount: usize,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vswprintf_p(
        _Options: ::std::os::raw::c_ulonglong,
        _Buffer: *mut wchar_t,
        _BufferCount: usize,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vswscanf(
        _Options: ::std::os::raw::c_ulonglong,
        _Buffer: *const wchar_t,
        _BufferCount: usize,
        _Format: *const wchar_t,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
pub type fpos_t = ::std::os::raw::c_longlong;
unsafe extern "C" {
    pub fn _get_stream_buffer_pointers(
        _Stream: *mut FILE,
        _Base: *mut *mut *mut ::std::os::raw::c_char,
        _Pointer: *mut *mut *mut ::std::os::raw::c_char,
        _Count: *mut *mut ::std::os::raw::c_int,
    ) -> errno_t;
}
unsafe extern "C" {
    pub fn clearerr_s(_Stream: *mut FILE) -> errno_t;
}
unsafe extern "C" {
    pub fn fopen_s(
        _Stream: *mut *mut FILE,
        _FileName: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
    ) -> errno_t;
}
unsafe extern "C" {
    pub fn fread_s(
        _Buffer: *mut ::std::os::raw::c_void,
        _BufferSize: usize,
        _ElementSize: usize,
        _ElementCount: usize,
        _Stream: *mut FILE,
    ) -> usize;
}
unsafe extern "C" {
    pub fn freopen_s(
        _Stream: *mut *mut FILE,
        _FileName: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
        _OldStream: *mut FILE,
    ) -> errno_t;
}
unsafe extern "C" {
    pub fn gets_s(
        _Buffer: *mut ::std::os::raw::c_char,
        _Size: rsize_t,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn tmpfile_s(_Stream: *mut *mut FILE) -> errno_t;
}
unsafe extern "C" {
    pub fn tmpnam_s(_Buffer: *mut ::std::os::raw::c_char, _Size: rsize_t) -> errno_t;
}
unsafe extern "C" {
    pub fn clearerr(_Stream: *mut FILE);
}
unsafe extern "C" {
    pub fn fclose(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _fcloseall() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _fdopen(
        _FileHandle: ::std::os::raw::c_int,
        _Mode: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn feof(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn ferror(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fflush(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fgetc(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _fgetchar() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fgetpos(_Stream: *mut FILE, _Position: *mut fpos_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fgets(
        _Buffer: *mut ::std::os::raw::c_char,
        _MaxCount: ::std::os::raw::c_int,
        _Stream: *mut FILE,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn _fileno(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _flushall() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fopen(
        _FileName: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn fputc(_Character: ::std::os::raw::c_int, _Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _fputchar(_Character: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fputs(
        _Buffer: *const ::std::os::raw::c_char,
        _Stream: *mut FILE,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fread(
        _Buffer: *mut ::std::os::raw::c_void,
        _ElementSize: ::std::os::raw::c_ulonglong,
        _ElementCount: ::std::os::raw::c_ulonglong,
        _Stream: *mut FILE,
    ) -> ::std::os::raw::c_ulonglong;
}
unsafe extern "C" {
    pub fn freopen(
        _FileName: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
        _Stream: *mut FILE,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn _fsopen(
        _FileName: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
        _ShFlag: ::std::os::raw::c_int,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn fsetpos(_Stream: *mut FILE, _Position: *const fpos_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fseek(
        _Stream: *mut FILE,
        _Offset: ::std::os::raw::c_long,
        _Origin: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _fseeki64(
        _Stream: *mut FILE,
        _Offset: ::std::os::raw::c_longlong,
        _Origin: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn ftell(_Stream: *mut FILE) -> ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn _ftelli64(_Stream: *mut FILE) -> ::std::os::raw::c_longlong;
}
unsafe extern "C" {
    pub fn fwrite(
        _Buffer: *const ::std::os::raw::c_void,
        _ElementSize: ::std::os::raw::c_ulonglong,
        _ElementCount: ::std::os::raw::c_ulonglong,
        _Stream: *mut FILE,
    ) -> ::std::os::raw::c_ulonglong;
}
unsafe extern "C" {
    pub fn getc(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn getchar() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _getmaxstdio() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _getw(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn perror(_ErrorMessage: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn _pclose(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _popen(
        _Command: *const ::std::os::raw::c_char,
        _Mode: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn putc(_Character: ::std::os::raw::c_int, _Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn putchar(_Character: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn puts(_Buffer: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _putw(_Word: ::std::os::raw::c_int, _Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn remove(_FileName: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rename(
        _OldFileName: *const ::std::os::raw::c_char,
        _NewFileName: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _unlink(_FileName: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn unlink(_FileName: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rewind(_Stream: *mut FILE);
}
unsafe extern "C" {
    pub fn _rmtmp() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn setbuf(_Stream: *mut FILE, _Buffer: *mut ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn _setmaxstdio(_Maximum: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn setvbuf(
        _Stream: *mut FILE,
        _Buffer: *mut ::std::os::raw::c_char,
        _Mode: ::std::os::raw::c_int,
        _Size: usize,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _tempnam(
        _DirectoryName: *const ::std::os::raw::c_char,
        _FilePrefix: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn tmpfile() -> *mut FILE;
}
unsafe extern "C" {
    pub fn tmpnam(_Buffer: *mut ::std::os::raw::c_char) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn ungetc(_Character: ::std::os::raw::c_int, _Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _lock_file(_Stream: *mut FILE);
}
unsafe extern "C" {
    pub fn _unlock_file(_Stream: *mut FILE);
}
unsafe extern "C" {
    pub fn _fclose_nolock(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _fflush_nolock(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _fgetc_nolock(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _fputc_nolock(
        _Character: ::std::os::raw::c_int,
        _Stream: *mut FILE,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _fread_nolock(
        _Buffer: *mut ::std::os::raw::c_void,
        _ElementSize: usize,
        _ElementCount: usize,
        _Stream: *mut FILE,
    ) -> usize;
}
unsafe extern "C" {
    pub fn _fread_nolock_s(
        _Buffer: *mut ::std::os::raw::c_void,
        _BufferSize: usize,
        _ElementSize: usize,
        _ElementCount: usize,
        _Stream: *mut FILE,
    ) -> usize;
}
unsafe extern "C" {
    pub fn _fseek_nolock(
        _Stream: *mut FILE,
        _Offset: ::std::os::raw::c_long,
        _Origin: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _fseeki64_nolock(
        _Stream: *mut FILE,
        _Offset: ::std::os::raw::c_longlong,
        _Origin: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _ftell_nolock(_Stream: *mut FILE) -> ::std::os::raw::c_long;
}
unsafe extern "C" {
    pub fn _ftelli64_nolock(_Stream: *mut FILE) -> ::std::os::raw::c_longlong;
}
unsafe extern "C" {
    pub fn _fwrite_nolock(
        _Buffer: *const ::std::os::raw::c_void,
        _ElementSize: usize,
        _ElementCount: usize,
        _Stream: *mut FILE,
    ) -> usize;
}
unsafe extern "C" {
    pub fn _getc_nolock(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _putc_nolock(
        _Character: ::std::os::raw::c_int,
        _Stream: *mut FILE,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _ungetc_nolock(
        _Character: ::std::os::raw::c_int,
        _Stream: *mut FILE,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __p__commode() -> *mut ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vfprintf(
        _Options: ::std::os::raw::c_ulonglong,
        _Stream: *mut FILE,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vfprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _Stream: *mut FILE,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vfprintf_p(
        _Options: ::std::os::raw::c_ulonglong,
        _Stream: *mut FILE,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _set_printf_count_output(_Value: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn _get_printf_count_output() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vfscanf(
        _Options: ::std::os::raw::c_ulonglong,
        _Stream: *mut FILE,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _Arglist: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vsprintf(
        _Options: ::std::os::raw::c_ulonglong,
        _Buffer: *mut ::std::os::raw::c_char,
        _BufferCount: usize,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vsprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _Buffer: *mut ::std::os::raw::c_char,
        _BufferCount: usize,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vsnprintf_s(
        _Options: ::std::os::raw::c_ulonglong,
        _Buffer: *mut ::std::os::raw::c_char,
        _BufferCount: usize,
        _MaxCount: usize,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vsprintf_p(
        _Options: ::std::os::raw::c_ulonglong,
        _Buffer: *mut ::std::os::raw::c_char,
        _BufferCount: usize,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn __stdio_common_vsscanf(
        _Options: ::std::os::raw::c_ulonglong,
        _Buffer: *const ::std::os::raw::c_char,
        _BufferCount: usize,
        _Format: *const ::std::os::raw::c_char,
        _Locale: _locale_t,
        _ArgList: va_list,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn tempnam(
        _Directory: *const ::std::os::raw::c_char,
        _FilePrefix: *const ::std::os::raw::c_char,
    ) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn fcloseall() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fdopen(
        _FileHandle: ::std::os::raw::c_int,
        _Format: *const ::std::os::raw::c_char,
    ) -> *mut FILE;
}
unsafe extern "C" {
    pub fn fgetchar() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fileno(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn flushall() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fputchar(_Ch: ::std::os::raw::c_int) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn getw(_Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn putw(_Ch: ::std::os::raw::c_int, _Stream: *mut FILE) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rmtmp() -> ::std::os::raw::c_int;
}
pub const resourcetype_t_t_sound: resourcetype_t = 0;
pub const resourcetype_t_t_skin: resourcetype_t = 1;
pub const resourcetype_t_t_model: resourcetype_t = 2;
pub const resourcetype_t_t_decal: resourcetype_t = 3;
pub const resourcetype_t_t_generic: resourcetype_t = 4;
pub const resourcetype_t_t_eventscript: resourcetype_t = 5;
pub const resourcetype_t_t_world: resourcetype_t = 6;
pub type resourcetype_t = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct _resourceinfo_t {
    pub size: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct resourceinfo_s {
    pub info: [_resourceinfo_t; 8usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type resourceinfo_t = resourceinfo_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct MD5Context_t {
    pub buf: [::std::os::raw::c_uint; 4usize],
    pub bits: [::std::os::raw::c_uint; 2usize],
    pub in_: [::std::os::raw::c_uchar; 64usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type CRC32_t = uint32;
unsafe extern "C" {
    pub fn CRC32_Init(pulCRC: *mut CRC32_t);
}
unsafe extern "C" {
    pub fn CRC32_Final(pulCRC: CRC32_t) -> CRC32_t;
}
unsafe extern "C" {
    pub fn CRC32_ProcessBuffer(
        pulCRC: *mut CRC32_t,
        p: *mut ::std::os::raw::c_void,
        len: ::std::os::raw::c_int,
    );
}
unsafe extern "C" {
    pub fn CRC32_ProcessByte(pulCRC: *mut CRC32_t, ch: ::std::os::raw::c_uchar);
}
unsafe extern "C" {
    pub fn CRC_File(
        crcvalue: *mut CRC32_t,
        pszFileName: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn COM_BlockSequenceCRCByte(
        base: *mut ::std::os::raw::c_uchar,
        length: ::std::os::raw::c_int,
        sequence: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_uchar;
}
unsafe extern "C" {
    pub fn MD5Init(context: *mut MD5Context_t);
}
unsafe extern "C" {
    pub fn MD5Update(
        context: *mut MD5Context_t,
        buf: *const ::std::os::raw::c_uchar,
        len: ::std::os::raw::c_uint,
    );
}
unsafe extern "C" {
    pub fn MD5Final(digest: *mut ::std::os::raw::c_uchar, context: *mut MD5Context_t);
}
unsafe extern "C" {
    pub fn Transform(buf: *mut ::std::os::raw::c_uint, in_: *const ::std::os::raw::c_uint);
}
unsafe extern "C" {
    pub fn MD5_Hash_File(
        digest: *mut ::std::os::raw::c_uchar,
        pszFileName: *mut ::std::os::raw::c_char,
        bUsefopen: ::std::os::raw::c_int,
        bSeed: ::std::os::raw::c_int,
        seed: *mut ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn MD5_Print(hash: *mut ::std::os::raw::c_uchar) -> *mut ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn MD5_Hash_CachedFile(
        digest: *mut ::std::os::raw::c_uchar,
        pCache: *mut ::std::os::raw::c_uchar,
        nFileSize: ::std::os::raw::c_int,
        bSeed: ::std::os::raw::c_int,
        seed: *mut ::std::os::raw::c_uint,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn CRC_MapFile(
        crcvalue: *mut CRC32_t,
        pszFileName: *mut ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct resource_s {
    pub szFileName: [::std::os::raw::c_char; 64usize],
    pub type_: resourcetype_t,
    pub nIndex: ::std::os::raw::c_int,
    pub nDownloadSize: ::std::os::raw::c_int,
    pub ucFlags: ::std::os::raw::c_uchar,
    pub rgucMD5_hash: [::std::os::raw::c_uchar; 16usize],
    pub playernum: ::std::os::raw::c_uchar,
    pub rguc_reserved: [::std::os::raw::c_uchar; 32usize],
    pub pNext: *mut resource_s,
    pub pPrev: *mut resource_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type resource_t = resource_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct customization_s {
    pub bInUse: qboolean,
    pub resource: resource_t,
    pub bTranslated: qboolean,
    pub nUserData1: ::std::os::raw::c_int,
    pub nUserData2: ::std::os::raw::c_int,
    pub pInfo: *mut ::std::os::raw::c_void,
    pub pBuffer: *mut ::std::os::raw::c_void,
    pub pNext: *mut customization_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type customization_t = customization_s;
unsafe extern "C" {
    pub fn COM_ClearCustomizationList(pHead: *mut customization_s, bCleanDecals: qboolean);
}
unsafe extern "C" {
    pub fn COM_CreateCustomization(
        pListHead: *mut customization_s,
        pResource: *mut resource_s,
        playernumber: ::std::os::raw::c_int,
        flags: ::std::os::raw::c_int,
        pCustomization: *mut *mut customization_s,
        nLumps: *mut ::std::os::raw::c_int,
    ) -> qboolean;
}
unsafe extern "C" {
    pub fn COM_SizeofResourceList(
        pList: *mut resource_s,
        ri: *mut resourceinfo_s,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cvar_s {
    pub name: *const ::std::os::raw::c_char,
    pub string: *const ::std::os::raw::c_char,
    pub flags: ::std::os::raw::c_int,
    pub value: f32,
    pub next: *mut cvar_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type cvar_t = cvar_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct client_textmessage_s {
    pub effect: ::std::os::raw::c_int,
    pub r1: byte,
    pub g1: byte,
    pub b1: byte,
    pub a1: byte,
    pub r2: byte,
    pub g2: byte,
    pub b2: byte,
    pub a2: byte,
    pub x: f32,
    pub y: f32,
    pub fadein: f32,
    pub fadeout: f32,
    pub holdtime: f32,
    pub fxtime: f32,
    pub pName: *const ::std::os::raw::c_char,
    pub pMessage: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type client_textmessage_t = client_textmessage_s;
pub const sequenceModifierBits_SEQUENCE_MODIFIER_EFFECT_BIT: sequenceModifierBits = 2;
pub const sequenceModifierBits_SEQUENCE_MODIFIER_POSITION_BIT: sequenceModifierBits = 4;
pub const sequenceModifierBits_SEQUENCE_MODIFIER_COLOR_BIT: sequenceModifierBits = 8;
pub const sequenceModifierBits_SEQUENCE_MODIFIER_COLOR2_BIT: sequenceModifierBits = 16;
pub const sequenceModifierBits_SEQUENCE_MODIFIER_FADEIN_BIT: sequenceModifierBits = 32;
pub const sequenceModifierBits_SEQUENCE_MODIFIER_FADEOUT_BIT: sequenceModifierBits = 64;
pub const sequenceModifierBits_SEQUENCE_MODIFIER_HOLDTIME_BIT: sequenceModifierBits = 128;
pub const sequenceModifierBits_SEQUENCE_MODIFIER_FXTIME_BIT: sequenceModifierBits = 256;
pub const sequenceModifierBits_SEQUENCE_MODIFIER_SPEAKER_BIT: sequenceModifierBits = 512;
pub const sequenceModifierBits_SEQUENCE_MODIFIER_LISTENER_BIT: sequenceModifierBits = 1024;
pub const sequenceModifierBits_SEQUENCE_MODIFIER_TEXTCHANNEL_BIT: sequenceModifierBits = 2048;
pub type sequenceModifierBits = ::std::os::raw::c_int;
pub use self::sequenceModifierBits as sequenceModifierBits_e;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_ERROR: sequenceCommandEnum_ = -1;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_PAUSE: sequenceCommandEnum_ = 0;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_FIRETARGETS: sequenceCommandEnum_ = 1;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_KILLTARGETS: sequenceCommandEnum_ = 2;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_TEXT: sequenceCommandEnum_ = 3;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_SOUND: sequenceCommandEnum_ = 4;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_GOSUB: sequenceCommandEnum_ = 5;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_SENTENCE: sequenceCommandEnum_ = 6;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_REPEAT: sequenceCommandEnum_ = 7;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_SETDEFAULTS: sequenceCommandEnum_ = 8;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_MODIFIER: sequenceCommandEnum_ = 9;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_POSTMODIFIER: sequenceCommandEnum_ = 10;
pub const sequenceCommandEnum__SEQUENCE_COMMAND_NOOP: sequenceCommandEnum_ = 11;
pub const sequenceCommandEnum__SEQUENCE_MODIFIER_EFFECT: sequenceCommandEnum_ = 12;
pub const sequenceCommandEnum__SEQUENCE_MODIFIER_POSITION: sequenceCommandEnum_ = 13;
pub const sequenceCommandEnum__SEQUENCE_MODIFIER_COLOR: sequenceCommandEnum_ = 14;
pub const sequenceCommandEnum__SEQUENCE_MODIFIER_COLOR2: sequenceCommandEnum_ = 15;
pub const sequenceCommandEnum__SEQUENCE_MODIFIER_FADEIN: sequenceCommandEnum_ = 16;
pub const sequenceCommandEnum__SEQUENCE_MODIFIER_FADEOUT: sequenceCommandEnum_ = 17;
pub const sequenceCommandEnum__SEQUENCE_MODIFIER_HOLDTIME: sequenceCommandEnum_ = 18;
pub const sequenceCommandEnum__SEQUENCE_MODIFIER_FXTIME: sequenceCommandEnum_ = 19;
pub const sequenceCommandEnum__SEQUENCE_MODIFIER_SPEAKER: sequenceCommandEnum_ = 20;
pub const sequenceCommandEnum__SEQUENCE_MODIFIER_LISTENER: sequenceCommandEnum_ = 21;
pub const sequenceCommandEnum__SEQUENCE_MODIFIER_TEXTCHANNEL: sequenceCommandEnum_ = 22;
pub type sequenceCommandEnum_ = ::std::os::raw::c_int;
pub use self::sequenceCommandEnum_ as sequenceCommandEnum_e;
pub const sequenceCommandType__SEQUENCE_TYPE_COMMAND: sequenceCommandType_ = 0;
pub const sequenceCommandType__SEQUENCE_TYPE_MODIFIER: sequenceCommandType_ = 1;
pub type sequenceCommandType_ = ::std::os::raw::c_int;
pub use self::sequenceCommandType_ as sequenceCommandType_e;
pub type sequenceCommandMapping_s = sequenceCommandMapping_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sequenceCommandMapping_ {
    pub commandEnum: sequenceCommandEnum_e,
    pub commandName: *const ::std::os::raw::c_char,
    pub commandType: sequenceCommandType_e,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type sequenceCommandLine_s = sequenceCommandLine_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sequenceCommandLine_ {
    pub commandType: ::std::os::raw::c_int,
    pub clientMessage: client_textmessage_t,
    pub speakerName: *mut ::std::os::raw::c_char,
    pub listenerName: *mut ::std::os::raw::c_char,
    pub soundFileName: *mut ::std::os::raw::c_char,
    pub sentenceName: *mut ::std::os::raw::c_char,
    pub fireTargetNames: *mut ::std::os::raw::c_char,
    pub killTargetNames: *mut ::std::os::raw::c_char,
    pub delay: f32,
    pub repeatCount: ::std::os::raw::c_int,
    pub textChannel: ::std::os::raw::c_int,
    pub modifierBitField: ::std::os::raw::c_int,
    pub nextCommandLine: *mut sequenceCommandLine_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type sequenceEntry_s = sequenceEntry_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sequenceEntry_ {
    pub fileName: *mut ::std::os::raw::c_char,
    pub entryName: *mut ::std::os::raw::c_char,
    pub firstCommand: *mut sequenceCommandLine_s,
    pub nextEntry: *mut sequenceEntry_s,
    pub isGlobal: qboolean,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type sentenceEntry_s = sentenceEntry_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sentenceEntry_ {
    pub data: *mut ::std::os::raw::c_char,
    pub nextEntry: *mut sentenceEntry_s,
    pub isGlobal: qboolean,
    pub index: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type sentenceGroupEntry_s = sentenceGroupEntry_;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct sentenceGroupEntry_ {
    pub groupName: *mut ::std::os::raw::c_char,
    pub numSentences: ::std::os::raw::c_uint,
    pub firstSentence: *mut sentenceEntry_s,
    pub nextEntry: *mut sentenceGroupEntry_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
unsafe extern "C" {
    pub fn SequenceGet(
        fileName: *const ::std::os::raw::c_char,
        entryName: *const ::std::os::raw::c_char,
    ) -> *mut sequenceEntry_s;
}
unsafe extern "C" {
    pub fn Sequence_ParseFile(fileName: *const ::std::os::raw::c_char, isGlobal: qboolean);
}
unsafe extern "C" {
    pub fn Sequence_OnLevelLoad(mapName: *const ::std::os::raw::c_char);
}
unsafe extern "C" {
    pub fn SequencePickSentence(
        groupName: *const ::std::os::raw::c_char,
        pickMethod: ::std::os::raw::c_int,
        picked: *mut ::std::os::raw::c_int,
    ) -> *mut sentenceEntry_s;
}
pub const ALERT_TYPE_at_notice: ALERT_TYPE = 0;
pub const ALERT_TYPE_at_console: ALERT_TYPE = 1;
pub const ALERT_TYPE_at_aiconsole: ALERT_TYPE = 2;
pub const ALERT_TYPE_at_warning: ALERT_TYPE = 3;
pub const ALERT_TYPE_at_error: ALERT_TYPE = 4;
pub const ALERT_TYPE_at_logged: ALERT_TYPE = 5;
pub type ALERT_TYPE = ::std::os::raw::c_int;
pub const PRINT_TYPE_print_console: PRINT_TYPE = 0;
pub const PRINT_TYPE_print_center: PRINT_TYPE = 1;
pub const PRINT_TYPE_print_chat: PRINT_TYPE = 2;
pub type PRINT_TYPE = ::std::os::raw::c_int;
pub const FORCE_TYPE_force_exactfile: FORCE_TYPE = 0;
pub const FORCE_TYPE_force_model_samebounds: FORCE_TYPE = 1;
pub const FORCE_TYPE_force_model_specifybounds: FORCE_TYPE = 2;
pub const FORCE_TYPE_force_model_specifybounds_if_avail: FORCE_TYPE = 3;
pub type FORCE_TYPE = ::std::os::raw::c_int;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TraceResult {
    pub fAllSolid: ::std::os::raw::c_int,
    pub fStartSolid: ::std::os::raw::c_int,
    pub fInOpen: ::std::os::raw::c_int,
    pub fInWater: ::std::os::raw::c_int,
    pub flFraction: f32,
    pub vecEndPos: vec3_t,
    pub flPlaneDist: f32,
    pub vecPlaneNormal: vec3_t,
    pub pHit: *mut edict_t,
    pub iHitgroup: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CDStatus {
    pub fPlaying: ::std::os::raw::c_int,
    pub fWasPlaying: ::std::os::raw::c_int,
    pub fInitialized: ::std::os::raw::c_int,
    pub fEnabled: ::std::os::raw::c_int,
    pub fPlayLooping: ::std::os::raw::c_int,
    pub cdvolume: f32,
    pub fCDRom: ::std::os::raw::c_int,
    pub fPlayTrack: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct enginefuncs_s {
    pub pfnPrecacheModel: ::std::option::Option<
        unsafe extern "C" fn(s: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub pfnPrecacheSound: ::std::option::Option<
        unsafe extern "C" fn(s: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub pfnSetModel: ::std::option::Option<
        unsafe extern "C" fn(e: *mut edict_t, m: *const ::std::os::raw::c_char),
    >,
    pub pfnModelIndex: ::std::option::Option<
        unsafe extern "C" fn(m: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub pfnModelFrames: ::std::option::Option<
        unsafe extern "C" fn(modelIndex: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >,
    pub pfnSetSize: ::std::option::Option<
        unsafe extern "C" fn(e: *mut edict_t, rgflMin: *const f32, rgflMax: *const f32),
    >,
    pub pfnChangeLevel: ::std::option::Option<
        unsafe extern "C" fn(s1: *const ::std::os::raw::c_char, s2: *const ::std::os::raw::c_char),
    >,
    pub pfnGetSpawnParms: ::std::option::Option<unsafe extern "C" fn(ent: *mut edict_t)>,
    pub pfnSaveSpawnParms: ::std::option::Option<unsafe extern "C" fn(ent: *mut edict_t)>,
    pub pfnVecToYaw: ::std::option::Option<unsafe extern "C" fn(rgflVector: *const f32) -> f32>,
    pub pfnVecToAngles: ::std::option::Option<
        unsafe extern "C" fn(rgflVectorIn: *const f32, rgflVectorOut: *mut f32),
    >,
    pub pfnMoveToOrigin: ::std::option::Option<
        unsafe extern "C" fn(
            ent: *mut edict_t,
            pflGoal: *const f32,
            dist: f32,
            iMoveType: ::std::os::raw::c_int,
        ),
    >,
    pub pfnChangeYaw: ::std::option::Option<unsafe extern "C" fn(ent: *mut edict_t)>,
    pub pfnChangePitch: ::std::option::Option<unsafe extern "C" fn(ent: *mut edict_t)>,
    pub pfnFindEntityByString: ::std::option::Option<
        unsafe extern "C" fn(
            pEdictStartSearchAfter: *mut edict_t,
            pszField: *const ::std::os::raw::c_char,
            pszValue: *const ::std::os::raw::c_char,
        ) -> *mut edict_t,
    >,
    pub pfnGetEntityIllum:
        ::std::option::Option<unsafe extern "C" fn(pEnt: *mut edict_t) -> ::std::os::raw::c_int>,
    pub pfnFindEntityInSphere: ::std::option::Option<
        unsafe extern "C" fn(
            pEdictStartSearchAfter: *mut edict_t,
            org: *const f32,
            rad: f32,
        ) -> *mut edict_t,
    >,
    pub pfnFindClientInPVS:
        ::std::option::Option<unsafe extern "C" fn(pEdict: *mut edict_t) -> *mut edict_t>,
    pub pfnEntitiesInPVS:
        ::std::option::Option<unsafe extern "C" fn(pplayer: *mut edict_t) -> *mut edict_t>,
    pub pfnMakeVectors: ::std::option::Option<unsafe extern "C" fn(rgflVector: *const f32)>,
    pub pfnAngleVectors: ::std::option::Option<
        unsafe extern "C" fn(
            rgflVector: *const f32,
            forward: *mut f32,
            right: *mut f32,
            up: *mut f32,
        ),
    >,
    pub pfnCreateEntity: ::std::option::Option<unsafe extern "C" fn() -> *mut edict_t>,
    pub pfnRemoveEntity: ::std::option::Option<unsafe extern "C" fn(e: *mut edict_t)>,
    pub pfnCreateNamedEntity: ::std::option::Option<
        unsafe extern "C" fn(className: ::std::os::raw::c_int) -> *mut edict_t,
    >,
    pub pfnMakeStatic: ::std::option::Option<unsafe extern "C" fn(ent: *mut edict_t)>,
    pub pfnEntIsOnFloor:
        ::std::option::Option<unsafe extern "C" fn(e: *mut edict_t) -> ::std::os::raw::c_int>,
    pub pfnDropToFloor:
        ::std::option::Option<unsafe extern "C" fn(e: *mut edict_t) -> ::std::os::raw::c_int>,
    pub pfnWalkMove: ::std::option::Option<
        unsafe extern "C" fn(
            ent: *mut edict_t,
            yaw: f32,
            dist: f32,
            iMode: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnSetOrigin:
        ::std::option::Option<unsafe extern "C" fn(e: *mut edict_t, rgflOrigin: *const f32)>,
    pub pfnEmitSound: ::std::option::Option<
        unsafe extern "C" fn(
            entity: *mut edict_t,
            channel: ::std::os::raw::c_int,
            sample: *const ::std::os::raw::c_char,
            volume: f32,
            attenuation: f32,
            fFlags: ::std::os::raw::c_int,
            pitch: ::std::os::raw::c_int,
        ),
    >,
    pub pfnEmitAmbientSound: ::std::option::Option<
        unsafe extern "C" fn(
            entity: *mut edict_t,
            pos: *mut f32,
            samp: *const ::std::os::raw::c_char,
            vol: f32,
            attenuation: f32,
            fFlags: ::std::os::raw::c_int,
            pitch: ::std::os::raw::c_int,
        ),
    >,
    pub pfnTraceLine: ::std::option::Option<
        unsafe extern "C" fn(
            v1: *const f32,
            v2: *const f32,
            fNoMonsters: ::std::os::raw::c_int,
            pentToSkip: *mut edict_t,
            ptr: *mut TraceResult,
        ),
    >,
    pub pfnTraceToss: ::std::option::Option<
        unsafe extern "C" fn(pent: *mut edict_t, pentToIgnore: *mut edict_t, ptr: *mut TraceResult),
    >,
    pub pfnTraceMonsterHull: ::std::option::Option<
        unsafe extern "C" fn(
            pEdict: *mut edict_t,
            v1: *const f32,
            v2: *const f32,
            fNoMonsters: ::std::os::raw::c_int,
            pentToSkip: *mut edict_t,
            ptr: *mut TraceResult,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnTraceHull: ::std::option::Option<
        unsafe extern "C" fn(
            v1: *const f32,
            v2: *const f32,
            fNoMonsters: ::std::os::raw::c_int,
            hullNumber: ::std::os::raw::c_int,
            pentToSkip: *mut edict_t,
            ptr: *mut TraceResult,
        ),
    >,
    pub pfnTraceModel: ::std::option::Option<
        unsafe extern "C" fn(
            v1: *const f32,
            v2: *const f32,
            hullNumber: ::std::os::raw::c_int,
            pent: *mut edict_t,
            ptr: *mut TraceResult,
        ),
    >,
    pub pfnTraceTexture: ::std::option::Option<
        unsafe extern "C" fn(
            pTextureEntity: *mut edict_t,
            v1: *const f32,
            v2: *const f32,
        ) -> *const ::std::os::raw::c_char,
    >,
    pub pfnTraceSphere: ::std::option::Option<
        unsafe extern "C" fn(
            v1: *const f32,
            v2: *const f32,
            fNoMonsters: ::std::os::raw::c_int,
            radius: f32,
            pentToSkip: *mut edict_t,
            ptr: *mut TraceResult,
        ),
    >,
    pub pfnGetAimVector: ::std::option::Option<
        unsafe extern "C" fn(ent: *mut edict_t, speed: f32, rgflReturn: *mut f32),
    >,
    pub pfnServerCommand:
        ::std::option::Option<unsafe extern "C" fn(str_: *const ::std::os::raw::c_char)>,
    pub pfnServerExecute: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnClientCommand: ::std::option::Option<
        unsafe extern "C" fn(pEdict: *mut edict_t, szFmt: *const ::std::os::raw::c_char, ...),
    >,
    pub pfnParticleEffect: ::std::option::Option<
        unsafe extern "C" fn(org: *const f32, dir: *const f32, color: f32, count: f32),
    >,
    pub pfnLightStyle: ::std::option::Option<
        unsafe extern "C" fn(style: ::std::os::raw::c_int, val: *const ::std::os::raw::c_char),
    >,
    pub pfnDecalIndex: ::std::option::Option<
        unsafe extern "C" fn(name: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub pfnPointContents: ::std::option::Option<
        unsafe extern "C" fn(rgflVector: *const f32) -> ::std::os::raw::c_int,
    >,
    pub pfnMessageBegin: ::std::option::Option<
        unsafe extern "C" fn(
            msg_dest: ::std::os::raw::c_int,
            msg_type: ::std::os::raw::c_int,
            pOrigin: *const f32,
            ed: *mut edict_t,
        ),
    >,
    pub pfnMessageEnd: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnWriteByte: ::std::option::Option<unsafe extern "C" fn(iValue: ::std::os::raw::c_int)>,
    pub pfnWriteChar: ::std::option::Option<unsafe extern "C" fn(iValue: ::std::os::raw::c_int)>,
    pub pfnWriteShort: ::std::option::Option<unsafe extern "C" fn(iValue: ::std::os::raw::c_int)>,
    pub pfnWriteLong: ::std::option::Option<unsafe extern "C" fn(iValue: ::std::os::raw::c_int)>,
    pub pfnWriteAngle: ::std::option::Option<unsafe extern "C" fn(flValue: f32)>,
    pub pfnWriteCoord: ::std::option::Option<unsafe extern "C" fn(flValue: f32)>,
    pub pfnWriteString:
        ::std::option::Option<unsafe extern "C" fn(sz: *const ::std::os::raw::c_char)>,
    pub pfnWriteEntity: ::std::option::Option<unsafe extern "C" fn(iValue: ::std::os::raw::c_int)>,
    pub pfnCVarRegister: ::std::option::Option<unsafe extern "C" fn(pCvar: *mut cvar_t)>,
    pub pfnCVarGetFloat: ::std::option::Option<
        unsafe extern "C" fn(szVarName: *const ::std::os::raw::c_char) -> f32,
    >,
    pub pfnCVarGetString: ::std::option::Option<
        unsafe extern "C" fn(
            szVarName: *const ::std::os::raw::c_char,
        ) -> *const ::std::os::raw::c_char,
    >,
    pub pfnCVarSetFloat: ::std::option::Option<
        unsafe extern "C" fn(szVarName: *const ::std::os::raw::c_char, flValue: f32),
    >,
    pub pfnCVarSetString: ::std::option::Option<
        unsafe extern "C" fn(
            szVarName: *const ::std::os::raw::c_char,
            szValue: *const ::std::os::raw::c_char,
        ),
    >,
    pub pfnAlertMessage: ::std::option::Option<
        unsafe extern "C" fn(atype: ALERT_TYPE, szFmt: *const ::std::os::raw::c_char, ...),
    >,
    pub pfnEngineFprintf: ::std::option::Option<
        unsafe extern "C" fn(
            pfile: *mut ::std::os::raw::c_void,
            szFmt: *const ::std::os::raw::c_char,
            ...
        ),
    >,
    pub pfnPvAllocEntPrivateData: ::std::option::Option<
        unsafe extern "C" fn(pEdict: *mut edict_t, cb: int32) -> *mut ::std::os::raw::c_void,
    >,
    pub pfnPvEntPrivateData: ::std::option::Option<
        unsafe extern "C" fn(pEdict: *mut edict_t) -> *mut ::std::os::raw::c_void,
    >,
    pub pfnFreeEntPrivateData: ::std::option::Option<unsafe extern "C" fn(pEdict: *mut edict_t)>,
    pub pfnSzFromIndex: ::std::option::Option<
        unsafe extern "C" fn(iString: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char,
    >,
    pub pfnAllocString: ::std::option::Option<
        unsafe extern "C" fn(szValue: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub pfnGetVarsOfEnt:
        ::std::option::Option<unsafe extern "C" fn(pEdict: *mut edict_t) -> *mut entvars_s>,
    pub pfnPEntityOfEntOffset: ::std::option::Option<
        unsafe extern "C" fn(iEntOffset: ::std::os::raw::c_int) -> *mut edict_t,
    >,
    pub pfnEntOffsetOfPEntity: ::std::option::Option<
        unsafe extern "C" fn(pEdict: *const edict_t) -> ::std::os::raw::c_int,
    >,
    pub pfnIndexOfEdict: ::std::option::Option<
        unsafe extern "C" fn(pEdict: *const edict_t) -> ::std::os::raw::c_int,
    >,
    pub pfnPEntityOfEntIndex: ::std::option::Option<
        unsafe extern "C" fn(iEntIndex: ::std::os::raw::c_int) -> *mut edict_t,
    >,
    pub pfnFindEntityByVars:
        ::std::option::Option<unsafe extern "C" fn(pvars: *mut entvars_s) -> *mut edict_t>,
    pub pfnGetModelPtr: ::std::option::Option<
        unsafe extern "C" fn(pEdict: *mut edict_t) -> *mut ::std::os::raw::c_void,
    >,
    pub pfnRegUserMsg: ::std::option::Option<
        unsafe extern "C" fn(
            pszName: *const ::std::os::raw::c_char,
            iSize: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnAnimationAutomove:
        ::std::option::Option<unsafe extern "C" fn(pEdict: *const edict_t, flTime: f32)>,
    pub pfnGetBonePosition: ::std::option::Option<
        unsafe extern "C" fn(
            pEdict: *const edict_t,
            iBone: ::std::os::raw::c_int,
            rgflOrigin: *mut f32,
            rgflAngles: *mut f32,
        ),
    >,
    pub pfnFunctionFromName:
        ::std::option::Option<unsafe extern "C" fn(pName: *const ::std::os::raw::c_char) -> uint32>,
    pub pfnNameForFunction: ::std::option::Option<
        unsafe extern "C" fn(function: uint32) -> *const ::std::os::raw::c_char,
    >,
    pub pfnClientPrintf: ::std::option::Option<
        unsafe extern "C" fn(
            pEdict: *mut edict_t,
            ptype: PRINT_TYPE,
            szMsg: *const ::std::os::raw::c_char,
        ),
    >,
    pub pfnServerPrint:
        ::std::option::Option<unsafe extern "C" fn(szMsg: *const ::std::os::raw::c_char)>,
    pub pfnCmd_Args: ::std::option::Option<unsafe extern "C" fn() -> *const ::std::os::raw::c_char>,
    pub pfnCmd_Argv: ::std::option::Option<
        unsafe extern "C" fn(argc: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char,
    >,
    pub pfnCmd_Argc: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub pfnGetAttachment: ::std::option::Option<
        unsafe extern "C" fn(
            pEdict: *const edict_t,
            iAttachment: ::std::os::raw::c_int,
            rgflOrigin: *mut f32,
            rgflAngles: *mut f32,
        ),
    >,
    pub pfnCRC32_Init: ::std::option::Option<unsafe extern "C" fn(pulCRC: *mut CRC32_t)>,
    pub pfnCRC32_ProcessBuffer: ::std::option::Option<
        unsafe extern "C" fn(
            pulCRC: *mut CRC32_t,
            p: *mut ::std::os::raw::c_void,
            len: ::std::os::raw::c_int,
        ),
    >,
    pub pfnCRC32_ProcessByte: ::std::option::Option<
        unsafe extern "C" fn(pulCRC: *mut CRC32_t, ch: ::std::os::raw::c_uchar),
    >,
    pub pfnCRC32_Final: ::std::option::Option<unsafe extern "C" fn(pulCRC: CRC32_t) -> CRC32_t>,
    pub pfnRandomLong:
        ::std::option::Option<unsafe extern "C" fn(lLow: int32, lHigh: int32) -> int32>,
    pub pfnRandomFloat: ::std::option::Option<unsafe extern "C" fn(flLow: f32, flHigh: f32) -> f32>,
    pub pfnSetView: ::std::option::Option<
        unsafe extern "C" fn(pClient: *const edict_t, pViewent: *const edict_t),
    >,
    pub pfnTime: ::std::option::Option<unsafe extern "C" fn() -> f32>,
    pub pfnCrosshairAngle:
        ::std::option::Option<unsafe extern "C" fn(pClient: *const edict_t, pitch: f32, yaw: f32)>,
    pub pfnLoadFileForMe: ::std::option::Option<
        unsafe extern "C" fn(
            filename: *const ::std::os::raw::c_char,
            pLength: *mut ::std::os::raw::c_int,
        ) -> *mut byte,
    >,
    pub pfnFreeFile:
        ::std::option::Option<unsafe extern "C" fn(buffer: *mut ::std::os::raw::c_void)>,
    pub pfnEndSection:
        ::std::option::Option<unsafe extern "C" fn(pszSectionName: *const ::std::os::raw::c_char)>,
    pub pfnCompareFileTime: ::std::option::Option<
        unsafe extern "C" fn(
            filename1: *mut ::std::os::raw::c_char,
            filename2: *mut ::std::os::raw::c_char,
            iCompare: *mut ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnGetGameDir:
        ::std::option::Option<unsafe extern "C" fn(szGetGameDir: *mut ::std::os::raw::c_char)>,
    pub pfnCvar_RegisterVariable:
        ::std::option::Option<unsafe extern "C" fn(variable: *mut cvar_t)>,
    pub pfnFadeClientVolume: ::std::option::Option<
        unsafe extern "C" fn(
            pEdict: *const edict_t,
            fadePercent: ::std::os::raw::c_int,
            fadeOutSeconds: ::std::os::raw::c_int,
            holdTime: ::std::os::raw::c_int,
            fadeInSeconds: ::std::os::raw::c_int,
        ),
    >,
    pub pfnSetClientMaxspeed:
        ::std::option::Option<unsafe extern "C" fn(pEdict: *const edict_t, fNewMaxspeed: f32)>,
    pub pfnCreateFakeClient: ::std::option::Option<
        unsafe extern "C" fn(netname: *const ::std::os::raw::c_char) -> *mut edict_t,
    >,
    pub pfnRunPlayerMove: ::std::option::Option<
        unsafe extern "C" fn(
            fakeclient: *mut edict_t,
            viewangles: *const f32,
            forwardmove: f32,
            sidemove: f32,
            upmove: f32,
            buttons: ::std::os::raw::c_ushort,
            impulse: byte,
            msec: byte,
        ),
    >,
    pub pfnNumberOfEntities: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub pfnGetInfoKeyBuffer:
        ::std::option::Option<unsafe extern "C" fn(e: *mut edict_t) -> *mut ::std::os::raw::c_char>,
    pub pfnInfoKeyValue: ::std::option::Option<
        unsafe extern "C" fn(
            infobuffer: *mut ::std::os::raw::c_char,
            key: *const ::std::os::raw::c_char,
        ) -> *mut ::std::os::raw::c_char,
    >,
    pub pfnSetKeyValue: ::std::option::Option<
        unsafe extern "C" fn(
            infobuffer: *mut ::std::os::raw::c_char,
            key: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        ),
    >,
    pub pfnSetClientKeyValue: ::std::option::Option<
        unsafe extern "C" fn(
            clientIndex: ::std::os::raw::c_int,
            infobuffer: *mut ::std::os::raw::c_char,
            key: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        ),
    >,
    pub pfnIsMapValid: ::std::option::Option<
        unsafe extern "C" fn(filename: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub pfnStaticDecal: ::std::option::Option<
        unsafe extern "C" fn(
            origin: *const f32,
            decalIndex: ::std::os::raw::c_int,
            entityIndex: ::std::os::raw::c_int,
            modelIndex: ::std::os::raw::c_int,
        ),
    >,
    pub pfnPrecacheGeneric: ::std::option::Option<
        unsafe extern "C" fn(s: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub pfnGetPlayerUserId:
        ::std::option::Option<unsafe extern "C" fn(e: *mut edict_t) -> ::std::os::raw::c_int>,
    pub pfnBuildSoundMsg: ::std::option::Option<
        unsafe extern "C" fn(
            entity: *mut edict_t,
            channel: ::std::os::raw::c_int,
            sample: *const ::std::os::raw::c_char,
            volume: f32,
            attenuation: f32,
            fFlags: ::std::os::raw::c_int,
            pitch: ::std::os::raw::c_int,
            msg_dest: ::std::os::raw::c_int,
            msg_type: ::std::os::raw::c_int,
            pOrigin: *const f32,
            ed: *mut edict_t,
        ),
    >,
    pub pfnIsDedicatedServer:
        ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub pfnCVarGetPointer: ::std::option::Option<
        unsafe extern "C" fn(szVarName: *const ::std::os::raw::c_char) -> *mut cvar_t,
    >,
    pub pfnGetPlayerWONId:
        ::std::option::Option<unsafe extern "C" fn(e: *mut edict_t) -> ::std::os::raw::c_uint>,
    pub pfnInfo_RemoveKey: ::std::option::Option<
        unsafe extern "C" fn(s: *mut ::std::os::raw::c_char, key: *const ::std::os::raw::c_char),
    >,
    pub pfnGetPhysicsKeyValue: ::std::option::Option<
        unsafe extern "C" fn(
            pClient: *const edict_t,
            key: *const ::std::os::raw::c_char,
        ) -> *const ::std::os::raw::c_char,
    >,
    pub pfnSetPhysicsKeyValue: ::std::option::Option<
        unsafe extern "C" fn(
            pClient: *const edict_t,
            key: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        ),
    >,
    pub pfnGetPhysicsInfoString: ::std::option::Option<
        unsafe extern "C" fn(pClient: *const edict_t) -> *const ::std::os::raw::c_char,
    >,
    pub pfnPrecacheEvent: ::std::option::Option<
        unsafe extern "C" fn(
            type_: ::std::os::raw::c_int,
            psz: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_ushort,
    >,
    pub pfnPlaybackEvent: ::std::option::Option<
        unsafe extern "C" fn(
            flags: ::std::os::raw::c_int,
            pInvoker: *const edict_t,
            eventindex: ::std::os::raw::c_ushort,
            delay: f32,
            origin: *mut f32,
            angles: *mut f32,
            fparam1: f32,
            fparam2: f32,
            iparam1: ::std::os::raw::c_int,
            iparam2: ::std::os::raw::c_int,
            bparam1: ::std::os::raw::c_int,
            bparam2: ::std::os::raw::c_int,
        ),
    >,
    pub pfnSetFatPVS:
        ::std::option::Option<unsafe extern "C" fn(org: *mut f32) -> *mut ::std::os::raw::c_uchar>,
    pub pfnSetFatPAS:
        ::std::option::Option<unsafe extern "C" fn(org: *mut f32) -> *mut ::std::os::raw::c_uchar>,
    pub pfnCheckVisibility: ::std::option::Option<
        unsafe extern "C" fn(
            entity: *const edict_t,
            pset: *mut ::std::os::raw::c_uchar,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnDeltaSetField: ::std::option::Option<
        unsafe extern "C" fn(pFields: *mut delta_s, fieldname: *const ::std::os::raw::c_char),
    >,
    pub pfnDeltaUnsetField: ::std::option::Option<
        unsafe extern "C" fn(pFields: *mut delta_s, fieldname: *const ::std::os::raw::c_char),
    >,
    pub pfnDeltaAddEncoder: ::std::option::Option<
        unsafe extern "C" fn(
            name: *const ::std::os::raw::c_char,
            conditionalencode: ::std::option::Option<
                unsafe extern "C" fn(
                    pFields: *mut delta_s,
                    from: *const ::std::os::raw::c_uchar,
                    to: *const ::std::os::raw::c_uchar,
                ),
            >,
        ),
    >,
    pub pfnGetCurrentPlayer: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub pfnCanSkipPlayer: ::std::option::Option<
        unsafe extern "C" fn(player: *const edict_t) -> ::std::os::raw::c_int,
    >,
    pub pfnDeltaFindField: ::std::option::Option<
        unsafe extern "C" fn(
            pFields: *mut delta_s,
            fieldname: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnDeltaSetFieldByIndex: ::std::option::Option<
        unsafe extern "C" fn(pFields: *mut delta_s, fieldNumber: ::std::os::raw::c_int),
    >,
    pub pfnDeltaUnsetFieldByIndex: ::std::option::Option<
        unsafe extern "C" fn(pFields: *mut delta_s, fieldNumber: ::std::os::raw::c_int),
    >,
    pub pfnSetGroupMask: ::std::option::Option<
        unsafe extern "C" fn(mask: ::std::os::raw::c_int, op: ::std::os::raw::c_int),
    >,
    pub pfnCreateInstancedBaseline: ::std::option::Option<
        unsafe extern "C" fn(
            classname: ::std::os::raw::c_int,
            baseline: *mut entity_state_s,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnCvar_DirectSet: ::std::option::Option<
        unsafe extern "C" fn(var: *mut cvar_s, value: *const ::std::os::raw::c_char),
    >,
    pub pfnForceUnmodified: ::std::option::Option<
        unsafe extern "C" fn(
            type_: FORCE_TYPE,
            mins: *mut f32,
            maxs: *mut f32,
            filename: *const ::std::os::raw::c_char,
        ),
    >,
    pub pfnGetPlayerStats: ::std::option::Option<
        unsafe extern "C" fn(
            pClient: *const edict_t,
            ping: *mut ::std::os::raw::c_int,
            packet_loss: *mut ::std::os::raw::c_int,
        ),
    >,
    pub pfnAddServerCommand: ::std::option::Option<
        unsafe extern "C" fn(
            cmd_name: *const ::std::os::raw::c_char,
            function: ::std::option::Option<unsafe extern "C" fn()>,
        ),
    >,
    pub pfnVoice_GetClientListening: ::std::option::Option<
        unsafe extern "C" fn(
            iReceiver: ::std::os::raw::c_int,
            iSender: ::std::os::raw::c_int,
        ) -> qboolean,
    >,
    pub pfnVoice_SetClientListening: ::std::option::Option<
        unsafe extern "C" fn(
            iReceiver: ::std::os::raw::c_int,
            iSender: ::std::os::raw::c_int,
            bListen: qboolean,
        ) -> qboolean,
    >,
    pub pfnGetPlayerAuthId: ::std::option::Option<
        unsafe extern "C" fn(e: *mut edict_t) -> *const ::std::os::raw::c_char,
    >,
    pub pfnSequenceGet: ::std::option::Option<
        unsafe extern "C" fn(
            fileName: *const ::std::os::raw::c_char,
            entryName: *const ::std::os::raw::c_char,
        ) -> *mut sequenceEntry_s,
    >,
    pub pfnSequencePickSentence: ::std::option::Option<
        unsafe extern "C" fn(
            groupName: *const ::std::os::raw::c_char,
            pickMethod: ::std::os::raw::c_int,
            picked: *mut ::std::os::raw::c_int,
        ) -> *mut sentenceEntry_s,
    >,
    pub pfnGetFileSize: ::std::option::Option<
        unsafe extern "C" fn(filename: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub pfnGetApproxWavePlayLen: ::std::option::Option<
        unsafe extern "C" fn(filepath: *const ::std::os::raw::c_char) -> ::std::os::raw::c_uint,
    >,
    pub pfnIsCareerMatch: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub pfnGetLocalizedStringLength: ::std::option::Option<
        unsafe extern "C" fn(label: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub pfnRegisterTutorMessageShown:
        ::std::option::Option<unsafe extern "C" fn(mid: ::std::os::raw::c_int)>,
    pub pfnGetTimesTutorMessageShown: ::std::option::Option<
        unsafe extern "C" fn(mid: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >,
    pub pfnProcessTutorMessageDecayBuffer: ::std::option::Option<
        unsafe extern "C" fn(
            buffer: *mut ::std::os::raw::c_int,
            bufferLength: ::std::os::raw::c_int,
        ),
    >,
    pub pfnConstructTutorMessageDecayBuffer: ::std::option::Option<
        unsafe extern "C" fn(
            buffer: *mut ::std::os::raw::c_int,
            bufferLength: ::std::os::raw::c_int,
        ),
    >,
    pub pfnResetTutorMessageDecayData: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnQueryClientCvarValue: ::std::option::Option<
        unsafe extern "C" fn(player: *const edict_t, cvarName: *const ::std::os::raw::c_char),
    >,
    pub pfnQueryClientCvarValue2: ::std::option::Option<
        unsafe extern "C" fn(
            player: *const edict_t,
            cvarName: *const ::std::os::raw::c_char,
            requestID: ::std::os::raw::c_int,
        ),
    >,
    pub pfnCheckParm: ::std::option::Option<
        unsafe extern "C" fn(
            pchCmdLineToken: *const ::std::os::raw::c_char,
            ppnext: *mut *mut ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type enginefuncs_t = enginefuncs_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct KeyValueData_s {
    pub szClassName: *const ::std::os::raw::c_char,
    pub szKeyName: *const ::std::os::raw::c_char,
    pub szValue: *const ::std::os::raw::c_char,
    pub fHandled: int32,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type KeyValueData = KeyValueData_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LEVELLIST {
    pub mapName: [::std::os::raw::c_char; 32usize],
    pub landmarkName: [::std::os::raw::c_char; 32usize],
    pub pentLandmark: *mut edict_t,
    pub vecLandmarkOrigin: vec3_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ENTITYTABLE {
    pub id: ::std::os::raw::c_int,
    pub pent: *mut edict_t,
    pub location: ::std::os::raw::c_int,
    pub size: ::std::os::raw::c_int,
    pub flags: ::std::os::raw::c_int,
    pub classname: string_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type SAVERESTOREDATA = saverestore_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct saverestore_s {
    pub pBaseData: *mut ::std::os::raw::c_char,
    pub pCurrentData: *mut ::std::os::raw::c_char,
    pub size: ::std::os::raw::c_int,
    pub bufferSize: ::std::os::raw::c_int,
    pub tokenSize: ::std::os::raw::c_int,
    pub tokenCount: ::std::os::raw::c_int,
    pub pTokens: *mut *mut ::std::os::raw::c_char,
    pub currentIndex: ::std::os::raw::c_int,
    pub tableCount: ::std::os::raw::c_int,
    pub connectionCount: ::std::os::raw::c_int,
    pub pTable: *mut ENTITYTABLE,
    pub levelList: [LEVELLIST; 16usize],
    pub fUseLandmark: ::std::os::raw::c_int,
    pub szLandmarkName: [::std::os::raw::c_char; 20usize],
    pub vecLandmarkOffset: vec3_t,
    pub time: f32,
    pub szCurrentMapName: [::std::os::raw::c_char; 32usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub const _fieldtypes_FIELD_FLOAT: _fieldtypes = 0;
pub const _fieldtypes_FIELD_STRING: _fieldtypes = 1;
pub const _fieldtypes_FIELD_ENTITY: _fieldtypes = 2;
pub const _fieldtypes_FIELD_CLASSPTR: _fieldtypes = 3;
pub const _fieldtypes_FIELD_EHANDLE: _fieldtypes = 4;
pub const _fieldtypes_FIELD_EVARS: _fieldtypes = 5;
pub const _fieldtypes_FIELD_EDICT: _fieldtypes = 6;
pub const _fieldtypes_FIELD_VECTOR: _fieldtypes = 7;
pub const _fieldtypes_FIELD_POSITION_VECTOR: _fieldtypes = 8;
pub const _fieldtypes_FIELD_POINTER: _fieldtypes = 9;
pub const _fieldtypes_FIELD_INTEGER: _fieldtypes = 10;
pub const _fieldtypes_FIELD_FUNCTION: _fieldtypes = 11;
pub const _fieldtypes_FIELD_BOOLEAN: _fieldtypes = 12;
pub const _fieldtypes_FIELD_SHORT: _fieldtypes = 13;
pub const _fieldtypes_FIELD_CHARACTER: _fieldtypes = 14;
pub const _fieldtypes_FIELD_TIME: _fieldtypes = 15;
pub const _fieldtypes_FIELD_MODELNAME: _fieldtypes = 16;
pub const _fieldtypes_FIELD_SOUNDNAME: _fieldtypes = 17;
pub const _fieldtypes_FIELD_TYPECOUNT: _fieldtypes = 18;
pub type _fieldtypes = ::std::os::raw::c_int;
pub use self::_fieldtypes as FIELDTYPE;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct TYPEDESCRIPTION {
    pub fieldType: FIELDTYPE,
    pub fieldName: *const ::std::os::raw::c_char,
    pub fieldOffset: ::std::os::raw::c_int,
    pub fieldSize: ::std::os::raw::c_short,
    pub flags: ::std::os::raw::c_short,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct DLL_FUNCTIONS {
    pub pfnGameInit: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnSpawn:
        ::std::option::Option<unsafe extern "C" fn(pent: *mut edict_t) -> ::std::os::raw::c_int>,
    pub pfnThink: ::std::option::Option<unsafe extern "C" fn(pent: *mut edict_t)>,
    pub pfnUse: ::std::option::Option<
        unsafe extern "C" fn(pentUsed: *mut edict_t, pentOther: *mut edict_t),
    >,
    pub pfnTouch: ::std::option::Option<
        unsafe extern "C" fn(pentTouched: *mut edict_t, pentOther: *mut edict_t),
    >,
    pub pfnBlocked: ::std::option::Option<
        unsafe extern "C" fn(pentBlocked: *mut edict_t, pentOther: *mut edict_t),
    >,
    pub pfnKeyValue: ::std::option::Option<
        unsafe extern "C" fn(pentKeyvalue: *mut edict_t, pkvd: *mut KeyValueData),
    >,
    pub pfnSave: ::std::option::Option<
        unsafe extern "C" fn(pent: *mut edict_t, pSaveData: *mut SAVERESTOREDATA),
    >,
    pub pfnRestore: ::std::option::Option<
        unsafe extern "C" fn(
            pent: *mut edict_t,
            pSaveData: *mut SAVERESTOREDATA,
            globalEntity: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnSetAbsBox: ::std::option::Option<unsafe extern "C" fn(pent: *mut edict_t)>,
    pub pfnSaveWriteFields: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut SAVERESTOREDATA,
            arg2: *const ::std::os::raw::c_char,
            arg3: *mut ::std::os::raw::c_void,
            arg4: *mut TYPEDESCRIPTION,
            arg5: ::std::os::raw::c_int,
        ),
    >,
    pub pfnSaveReadFields: ::std::option::Option<
        unsafe extern "C" fn(
            arg1: *mut SAVERESTOREDATA,
            arg2: *const ::std::os::raw::c_char,
            arg3: *mut ::std::os::raw::c_void,
            arg4: *mut TYPEDESCRIPTION,
            arg5: ::std::os::raw::c_int,
        ),
    >,
    pub pfnSaveGlobalState: ::std::option::Option<unsafe extern "C" fn(arg1: *mut SAVERESTOREDATA)>,
    pub pfnRestoreGlobalState:
        ::std::option::Option<unsafe extern "C" fn(arg1: *mut SAVERESTOREDATA)>,
    pub pfnResetGlobalState: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnClientConnect: ::std::option::Option<
        unsafe extern "C" fn(
            pEntity: *mut edict_t,
            pszName: *const ::std::os::raw::c_char,
            pszAddress: *const ::std::os::raw::c_char,
            szRejectReason: *mut ::std::os::raw::c_char,
        ) -> qboolean,
    >,
    pub pfnClientDisconnect: ::std::option::Option<unsafe extern "C" fn(pEntity: *mut edict_t)>,
    pub pfnClientKill: ::std::option::Option<unsafe extern "C" fn(pEntity: *mut edict_t)>,
    pub pfnClientPutInServer: ::std::option::Option<unsafe extern "C" fn(pEntity: *mut edict_t)>,
    pub pfnClientCommand: ::std::option::Option<unsafe extern "C" fn(pEntity: *mut edict_t)>,
    pub pfnClientUserInfoChanged: ::std::option::Option<
        unsafe extern "C" fn(pEntity: *mut edict_t, infobuffer: *mut ::std::os::raw::c_char),
    >,
    pub pfnServerActivate: ::std::option::Option<
        unsafe extern "C" fn(
            pEdictList: *mut edict_t,
            edictCount: ::std::os::raw::c_int,
            clientMax: ::std::os::raw::c_int,
        ),
    >,
    pub pfnServerDeactivate: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnPlayerPreThink: ::std::option::Option<unsafe extern "C" fn(pEntity: *mut edict_t)>,
    pub pfnPlayerPostThink: ::std::option::Option<unsafe extern "C" fn(pEntity: *mut edict_t)>,
    pub pfnStartFrame: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnParmsNewLevel: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnParmsChangeLevel: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnGetGameDescription:
        ::std::option::Option<unsafe extern "C" fn() -> *const ::std::os::raw::c_char>,
    pub pfnPlayerCustomization: ::std::option::Option<
        unsafe extern "C" fn(pEntity: *mut edict_t, pCustom: *mut customization_t),
    >,
    pub pfnSpectatorConnect: ::std::option::Option<unsafe extern "C" fn(pEntity: *mut edict_t)>,
    pub pfnSpectatorDisconnect: ::std::option::Option<unsafe extern "C" fn(pEntity: *mut edict_t)>,
    pub pfnSpectatorThink: ::std::option::Option<unsafe extern "C" fn(pEntity: *mut edict_t)>,
    pub pfnSys_Error:
        ::std::option::Option<unsafe extern "C" fn(error_string: *const ::std::os::raw::c_char)>,
    pub pfnPM_Move:
        ::std::option::Option<unsafe extern "C" fn(ppmove: *mut playermove_s, server: qboolean)>,
    pub pfnPM_Init: ::std::option::Option<unsafe extern "C" fn(ppmove: *mut playermove_s)>,
    pub pfnPM_FindTextureType: ::std::option::Option<
        unsafe extern "C" fn(name: *const ::std::os::raw::c_char) -> ::std::os::raw::c_char,
    >,
    pub pfnSetupVisibility: ::std::option::Option<
        unsafe extern "C" fn(
            pViewEntity: *mut edict_s,
            pClient: *mut edict_s,
            pvs: *mut *mut ::std::os::raw::c_uchar,
            pas: *mut *mut ::std::os::raw::c_uchar,
        ),
    >,
    pub pfnUpdateClientData: ::std::option::Option<
        unsafe extern "C" fn(
            ent: *const edict_s,
            sendweapons: ::std::os::raw::c_int,
            cd: *mut clientdata_s,
        ),
    >,
    pub pfnAddToFullPack: ::std::option::Option<
        unsafe extern "C" fn(
            state: *mut entity_state_s,
            e: ::std::os::raw::c_int,
            ent: *mut edict_t,
            host: *mut edict_t,
            hostflags: ::std::os::raw::c_int,
            player: ::std::os::raw::c_int,
            pSet: *mut ::std::os::raw::c_uchar,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnCreateBaseline: ::std::option::Option<
        unsafe extern "C" fn(
            player: ::std::os::raw::c_int,
            eindex: ::std::os::raw::c_int,
            baseline: *mut entity_state_s,
            entity: *mut edict_s,
            playermodelindex: ::std::os::raw::c_int,
            player_mins: *mut vec_t,
            player_maxs: *mut vec_t,
        ),
    >,
    pub pfnRegisterEncoders: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnGetWeaponData: ::std::option::Option<
        unsafe extern "C" fn(
            player: *mut edict_s,
            info: *mut weapon_data_s,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnCmdStart: ::std::option::Option<
        unsafe extern "C" fn(
            player: *const edict_t,
            cmd: *const usercmd_s,
            random_seed: ::std::os::raw::c_uint,
        ),
    >,
    pub pfnCmdEnd: ::std::option::Option<unsafe extern "C" fn(player: *const edict_t)>,
    pub pfnConnectionlessPacket: ::std::option::Option<
        unsafe extern "C" fn(
            net_from: *const netadr_s,
            args: *const ::std::os::raw::c_char,
            response_buffer: *mut ::std::os::raw::c_char,
            response_buffer_size: *mut ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnGetHullBounds: ::std::option::Option<
        unsafe extern "C" fn(
            hullnumber: ::std::os::raw::c_int,
            mins: *mut f32,
            maxs: *mut f32,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnCreateInstancedBaselines: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnInconsistentFile: ::std::option::Option<
        unsafe extern "C" fn(
            player: *const edict_s,
            filename: *const ::std::os::raw::c_char,
            disconnect_message: *mut ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnAllowLagCompensation:
        ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
unsafe extern "C" {
    pub static mut gEntityInterface: DLL_FUNCTIONS;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct NEW_DLL_FUNCTIONS {
    pub pfnOnFreeEntPrivateData: ::std::option::Option<unsafe extern "C" fn(pEnt: *mut edict_t)>,
    pub pfnGameShutdown: ::std::option::Option<unsafe extern "C" fn()>,
    pub pfnShouldCollide: ::std::option::Option<
        unsafe extern "C" fn(
            pentTouched: *mut edict_t,
            pentOther: *mut edict_t,
        ) -> ::std::os::raw::c_int,
    >,
    pub pfnCvarValue: ::std::option::Option<
        unsafe extern "C" fn(pEnt: *const edict_t, value: *const ::std::os::raw::c_char),
    >,
    pub pfnCvarValue2: ::std::option::Option<
        unsafe extern "C" fn(
            pEnt: *const edict_t,
            requestID: ::std::os::raw::c_int,
            cvarName: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        ),
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
};
pub type NEW_DLL_FUNCTIONS_FN = ::std::option::Option<
    unsafe extern "C" fn(
        pFunctionTable: *mut NEW_DLL_FUNCTIONS,
        interfaceVersion: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
unsafe extern "C" {
    pub static mut gNewDLLFunctions: NEW_DLL_FUNCTIONS;
}
pub type APIFUNCTION = ::std::option::Option<
    unsafe extern "C" fn(
        pFunctionTable: *mut DLL_FUNCTIONS,
        interfaceVersion: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
pub type APIFUNCTION2 = ::std::option::Option<
    unsafe extern "C" fn(
        pFunctionTable: *mut DLL_FUNCTIONS,
        interfaceVersion: *mut ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int,
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_locale_data {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct __crt_multibyte_data {
    pub _address: u8,
}
pub type __builtin_va_list = *mut ::std::os::raw::c_char;
#[repr(C)]
#[derive(Debug)]
pub struct delta_s {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct entity_state_s {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct playermove_s {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct clientdata_s {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct weapon_data_s {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug)]
pub struct netadr_s {
    _unused: [u8; 0],
}
