[package]
name = "test_chat"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Demonstration plugin showcasing chat middleware, custom prefixing, and placeholders"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
goldsrc = { workspace = true }
goldsrc-macros = { workspace = true }
