[package]
name = "test_menu"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Declarative multi-page and DHUD menu verification plugin"

[lib]
crate-type = ["cdylib"]
doctest = false

[dependencies]
goldsrc = { workspace = true }
