[package]
name = "goldsrc"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Public framework (SDK) for GoldSrc.rs plugin developers"

[dependencies]
goldsrc-api = { workspace = true }
goldsrc-macros = { workspace = true }
crossbeam-channel = { workspace = true, optional = true }
serde = { workspace = true, optional = true }
log = { workspace = true }

[features]
default = ["ecs", "menu", "task", "serde"]
ecs = []
menu = []
task = ["dep:crossbeam-channel"]
serde = ["dep:serde", "goldsrc-api/serde"]
rules = ["goldsrc-api/rules"]
gamedata = ["goldsrc-api/gamedata"]

